// ===== DATABASE (localStorage) =====
const DB_KEY = 'dubai_guide_db';

const DEFAULT_DATA = {
  hotels: [
    // === 7 STARS / ULTRA LUXURY ===
    { id:1, name:"Burj Al Arab", nameEn:"Burj Al Arab Jumeirah", category:"hotels", subcategory:"7star", stars:7, description:"המלון הסמלי ביותר בדובאי בצורת מפרש, עם שירות 24/7 ייחודי וסוויטות דו-קומתיות.", image:"images/hotels/hotel_1.jpeg", rating:4.9, price:"$$$$$", priceRange:"₪4,000-25,000 ללילה", address:"Jumeirah Beach Road", lat:25.1412, lng:55.1855, phone:"+971-4-301-7777", tags:["7 כוכבים","מפרש","אייקוני"], featured:true },
    { id:2, name:"Atlantis The Royal", nameEn:"Atlantis The Royal", category:"hotels", subcategory:"7star", stars:7, description:"מלון חדש ומרהיב על הפאלם עם 17 מסעדות ובריכות ספקטקולריות.", image:"images/hotels/hotel_2.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪2,000-40,000 ללילה", address:"Palm Jumeirah", lat:25.1304, lng:55.1171, phone:"+971-4-426-2000", tags:["7 כוכבים","פאלם","חדש"], featured:true },
    { id:3, name:"Armani Hotel Dubai", nameEn:"Armani Hotel Dubai", category:"hotels", subcategory:"7star", stars:7, description:"בתוך ברג' חליפה, מעוצב אישית על ידי ג'ורג'יו ארמאני.", image:"images/hotels/hotel_3.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪2,500-15,000 ללילה", address:"Burj Khalifa, Downtown", lat:25.1972, lng:55.2744, phone:"+971-4-888-3888", tags:["7 כוכבים","ארמאני","עיצוב"], featured:true },
    { id:4, name:"Bvlgari Resort Dubai", nameEn:"Bvlgari Resort Dubai", category:"hotels", subcategory:"7star", stars:7, description:"מלון בלעדי על אי פרטי בצורת סוס ים, מעוצב במותג בולגרי.", image:"images/hotels/hotel_4.jpeg", rating:4.9, price:"$$$$$", priceRange:"₪2,200-90,000 ללילה", address:"Jumeirah Bay Island", lat:25.2050, lng:55.2350, phone:"+971-4-777-5555", tags:["7 כוכבים","אי פרטי","בולגרי"], featured:true },
    { id:5, name:"The Lana - Dorchester", nameEn:"The Lana Dorchester Collection", category:"hotels", subcategory:"7star", stars:7, description:"חבר בשרשרת דורצ'סטר, עם נוף מרהיב לתעלת דובאי.", image:"images/hotels/hotel_5.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪3,400-92,000 ללילה", address:"Business Bay", lat:25.1867, lng:55.2625, phone:"+971-4-220-0000", tags:["7 כוכבים","דורצ'סטר","חדש"], featured:false },
    { id:6, name:"One&Only The Palm", nameEn:"One&Only The Palm", category:"hotels", subcategory:"7star", stars:7, description:"מלון בוטיק אינטימי על הפאלם עם גינות ים תיכוניות ושירות יוצא דופן.", image:"images/hotels/hotel_6.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪2,600-18,000 ללילה", address:"Palm Jumeirah", lat:25.1150, lng:55.1380, phone:"+971-4-440-1010", tags:["7 כוכבים","בוטיק","פאלם"], featured:false },
    { id:7, name:"One&Only Royal Mirage", nameEn:"One&Only Royal Mirage", category:"hotels", subcategory:"7star", stars:7, description:"קסר ערבי אגדי על חוף הים עם גני דקלים ואווירה רומנטית.", image:"images/hotels/hotel_7.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪1,600-12,000 ללילה", address:"King Salman St, Jumeirah", lat:25.0940, lng:55.1500, phone:"+971-4-399-9999", tags:["7 כוכבים","ארמון","רומנטי"], featured:false },
    { id:8, name:"Four Seasons Jumeirah", nameEn:"Four Seasons Resort Dubai Jumeirah Beach", category:"hotels", subcategory:"7star", stars:7, description:"נופש על 270 מ' של חוף טבעי עם חדרים בגווני פסטל.", image:"images/hotels/hotel_8.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪2,000-14,000 ללילה", address:"Jumeirah Beach", lat:25.2100, lng:55.2500, phone:"+971-4-270-7777", tags:["7 כוכבים","חוף","פור סיזנס"], featured:false },
    { id:9, name:"Four Seasons DIFC", nameEn:"Four Seasons Hotel DIFC", category:"hotels", subcategory:"7star", stars:7, description:"מלון עירוני במרכז הפיננסי עם אמנות עכשווית ומסעדות מדהימות.", image:"images/hotels/hotel_9.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪1,800-10,000 ללילה", address:"DIFC", lat:25.2135, lng:55.2825, phone:"+971-4-506-0000", tags:["7 כוכבים","עסקים","DIFC"], featured:false },
    { id:10, name:"Palazzo Versace", nameEn:"Palazzo Versace Dubai", category:"hotels", subcategory:"7star", stars:7, description:"ארמון איטלקי על גדות דובאי קריק, כל ריהוטו תוכנן על ידי וורסאצ'ה.", image:"images/hotels/hotel_10.jpeg", rating:4.6, price:"$$$$$", priceRange:"₪1,500-10,000 ללילה", address:"Al Jaddaf", lat:25.2243, lng:55.3524, phone:"+971-4-556-8888", tags:["7 כוכבים","וורסאצ'ה","ארמון"], featured:false },
    { id:11, name:"Jumeirah Al Qasr", nameEn:"Jumeirah Al Qasr", category:"hotels", subcategory:"7star", stars:7, description:"ארמון הים של מתחם מדינת ג'ומיירה עם תעלות מים.", image:"images/hotels/hotel_11.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪1,800-15,000 ללילה", address:"Madinat Jumeirah", lat:25.1345, lng:55.1842, phone:"+971-4-366-8888", tags:["7 כוכבים","ארמון","ג'ומיירה"], featured:false },
    { id:12, name:"Jumeirah Marsa Al Arab", nameEn:"Jumeirah Marsa Al Arab", category:"hotels", subcategory:"7star", stars:7, description:"ב-50 המלונות הטובים בעולם 2025, עם עיצוב ימי מדהים.", image:"images/hotels/hotel_12.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪2,500-20,000 ללילה", address:"Umm Suqeim 3", lat:25.1400, lng:55.1860, phone:"+971-4-366-7777", tags:["7 כוכבים","חדש","ימי"], featured:false },
    { id:13, name:"Waldorf Astoria Palm", nameEn:"Waldorf Astoria Dubai Palm Jumeirah", category:"hotels", subcategory:"7star", stars:7, description:"וולדורף-אסטוריה על חוף הפאלם עם מסעדת שף מישלן.", image:"images/hotels/hotel_13.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪1,500-9,000 ללילה", address:"Palm Jumeirah", lat:25.1200, lng:55.1300, phone:"+971-4-818-2222", tags:["7 כוכבים","וולדורף","חוף"], featured:false },
    { id:14, name:"FIVE Palm Jumeirah", nameEn:"FIVE Palm Jumeirah", category:"hotels", subcategory:"7star", stars:7, description:"מלון בוטיק-מסיבות עם מסיבות הגג המפורסמות ביותר בדובאי.", image:"images/hotels/hotel_14.jpeg", rating:4.5, price:"$$$$", priceRange:"₪1,200-7,000 ללילה", address:"Palm Jumeirah West", lat:25.1180, lng:55.1250, phone:"+971-4-455-9999", tags:["7 כוכבים","מסיבות","גג"], featured:false },
    { id:15, name:"Atlantis The Palm", nameEn:"Atlantis The Palm", category:"hotels", subcategory:"7star", stars:7, description:"המלון המקורי על הפאלם עם פארק מים Aquaventure ואקוריום.", image:"images/hotels/hotel_15.jpeg", rating:4.7, price:"$$$$", priceRange:"₪1,000-12,000 ללילה", address:"Palm Jumeirah", lat:25.1304, lng:55.1171, phone:"+971-4-426-2000", tags:["7 כוכבים","פארק מים","משפחות"], featured:true },
    { id:16, name:"Address Downtown", nameEn:"Address Downtown Dubai", category:"hotels", subcategory:"7star", stars:7, description:"מגדל זהב מעל מזרקת דובאי, נוף מפורסם לברג' חליפה.", image:"images/hotels/hotel_16.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,200-8,000 ללילה", address:"Downtown Dubai", lat:25.1972, lng:55.2744, phone:"+971-4-436-8888", tags:["7 כוכבים","Downtown","מזרקה"], featured:false },
    { id:17, name:"St. Regis The Palm", nameEn:"The St. Regis Dubai The Palm", category:"hotels", subcategory:"7star", stars:7, description:"שירות Bespoke אישי ומסעדה של Heston Blumenthal.", image:"images/hotels/hotel_17.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,400-9,000 ללילה", address:"Palm Jumeirah", lat:25.1250, lng:55.1350, phone:"+971-4-218-0000", tags:["7 כוכבים","St.Regis","פאלם"], featured:false },
    { id:18, name:"FIVE Jumeirah Village", nameEn:"FIVE Jumeirah Village", category:"hotels", subcategory:"7star", stars:7, description:"מגדל עם 5 בריכות ואחד ממועדוני הגג הפופולריים.", image:"images/hotels/hotel_18.jpeg", rating:4.4, price:"$$$", priceRange:"₪900-5,000 ללילה", address:"JVC", lat:25.0650, lng:55.2100, phone:"+971-4-455-5555", tags:["7 כוכבים","בריכות","גג"], featured:false },
    { id:19, name:"Raffles The Palm", nameEn:"Raffles The Palm Dubai", category:"hotels", subcategory:"7star", stars:7, description:"רפאלס על הפאלם עם ספא עולמי ואחת הבריכות הגדולות בדובאי.", image:"images/hotels/hotel_19.jpeg", rating:4.7, price:"$$$$", priceRange:"₪1,300-8,500 ללילה", address:"Palm Jumeirah West", lat:25.1220, lng:55.1280, phone:"+971-4-248-8888", tags:["7 כוכבים","רפאלס","ספא"], featured:false },
    { id:20, name:"Jumeirah Al Naseem", nameEn:"Jumeirah Al Naseem", category:"hotels", subcategory:"7star", stars:7, description:"חלק ממתחם מדינת ג'ומיירה עם חוף פרטי וגן חיות ים.", image:"images/hotels/hotel_20.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,400-8,000 ללילה", address:"Madinat Jumeirah", lat:25.1350, lng:55.1850, phone:"+971-4-366-9999", tags:["7 כוכבים","חוף","ג'ומיירה"], featured:false },

    // === 5 STARS ===
    { id:21, name:"Sofitel The Palm", nameEn:"Sofitel Dubai The Palm", category:"hotels", subcategory:"5star", stars:5, description:"אתר נופש צרפתי-ערבי מפואר על הפאלם עם גינות טרופיות.", image:"images/hotels/hotel_21.jpeg", rating:4.5, price:"$$$", priceRange:"₪900-4,000 ללילה", address:"Palm Jumeirah East", lat:25.1280, lng:55.1450, phone:"+971-4-455-6677", tags:["5 כוכבים","צרפתי","פאלם"], featured:true },
    { id:22, name:"Sofitel JBR", nameEn:"Sofitel Dubai Jumeirah Beach", category:"hotels", subcategory:"5star", stars:5, description:"מלון סופיטל על חוף JBR עם מסעדה צרפתית מצוינת.", image:"images/hotels/hotel_22.jpeg", rating:4.4, price:"$$$", priceRange:"₪800-3,500 ללילה", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-448-4848", tags:["5 כוכבים","JBR","חוף"], featured:false },
    { id:23, name:"Fairmont The Palm", nameEn:"Fairmont The Palm", category:"hotels", subcategory:"5star", stars:5, description:"מלון פיירמונט מפואר עם חוף פרטי וספא עולמי.", image:"images/hotels/hotel_23.jpeg", rating:4.5, price:"$$$", priceRange:"₪850-4,500 ללילה", address:"Palm Jumeirah", lat:25.1260, lng:55.1400, phone:"+971-4-457-3388", tags:["5 כוכבים","פיירמונט","חוף"], featured:false },
    { id:24, name:"Fairmont Dubai", nameEn:"Fairmont Dubai", category:"hotels", subcategory:"5star", stars:5, description:"מלון דגל בלב מרכז דובאי מול מרכז הסחר העולמי.", image:"images/hotels/hotel_24.jpeg", rating:4.4, price:"$$$", priceRange:"₪700-3,500 ללילה", address:"Sheikh Zayed Road", lat:25.2256, lng:55.2688, phone:"+971-4-332-5555", tags:["5 כוכבים","מרכזי","עסקים"], featured:false },
    { id:25, name:"Raffles Dubai", nameEn:"Raffles Dubai", category:"hotels", subcategory:"5star", stars:5, description:"פירמידת רפאלס ליד וואפי סיטי עם גינת גג מרהיבה.", image:"https://images.pexels.com/photos/31820069/pexels-photo-31820069.jpeg", rating:4.6, price:"$$$", priceRange:"₪900-4,500 ללילה", address:"Wafi City, Oud Metha", lat:25.2200, lng:55.3200, phone:"+971-4-324-8888", tags:["5 כוכבים","פירמידה","רפאלס"], featured:false },
    { id:26, name:"Sheraton Grand Dubai", nameEn:"Sheraton Grand Hotel Dubai", category:"hotels", subcategory:"5star", stars:5, description:"שרתון פרמיום על שייח' זייד רוד עם נוף פנורמי ובריכה על הגג.", image:"https://images.pexels.com/photos/30245006/pexels-photo-30245006.jpeg", rating:4.3, price:"$$$", priceRange:"₪650-2,800 ללילה", address:"Sheikh Zayed Road", lat:25.2150, lng:55.2780, phone:"+971-4-507-6666", tags:["5 כוכבים","שרתון","נוף"], featured:false },
    { id:27, name:"Westin Mina Seyahi", nameEn:"Westin Dubai Mina Seyahi", category:"hotels", subcategory:"5star", stars:5, description:"מלון וסטין על חוף הים עם חוף פרטי וגישה ל-Marina.", image:"https://images.pexels.com/photos/34596088/pexels-photo-34596088.jpeg", rating:4.4, price:"$$$", priceRange:"₪700-3,000 ללילה", address:"Dubai Marina", lat:25.0900, lng:55.1500, phone:"+971-4-399-4141", tags:["5 כוכבים","חוף","מרינה"], featured:false },
    { id:28, name:"Hilton Al Habtoor", nameEn:"Hilton Dubai Al Habtoor City", category:"hotels", subcategory:"5star", stars:5, description:"חלק ממתחם Al Habtoor City עם מופעי לה סירק.", image:"https://images.pexels.com/photos/14749935/pexels-photo-14749935.jpeg", rating:4.3, price:"$$$", priceRange:"₪700-3,200 ללילה", address:"Al Habtoor City", lat:25.1850, lng:55.2448, phone:"+971-4-435-5555", tags:["5 כוכבים","הילטון","בידור"], featured:false },
    { id:29, name:"InterContinental Festival", nameEn:"InterContinental Dubai Festival City", category:"hotels", subcategory:"5star", stars:5, description:"מלון על קו המים של דובאי קריק עם נוף לברג' חליפה.", image:"https://images.pexels.com/photos/14749879/pexels-photo-14749879.jpeg", rating:4.5, price:"$$$", priceRange:"₪750-3,500 ללילה", address:"Festival City", lat:25.2243, lng:55.3524, phone:"+971-4-701-1111", tags:["5 כוכבים","קריק","נוף"], featured:false },
    { id:30, name:"Jumeirah Beach Hotel", nameEn:"Jumeirah Beach Hotel", category:"hotels", subcategory:"5star", stars:5, description:"מלון הגלים האייקוני עם נוף לברג' אל-ערב ו-19 מסעדות.", image:"https://images.pexels.com/photos/31851252/pexels-photo-31851252.jpeg", rating:4.5, price:"$$$", priceRange:"₪800-4,000 ללילה", address:"Jumeirah Beach Road", lat:25.1412, lng:55.1855, phone:"+971-4-348-0000", tags:["5 כוכבים","גלים","חוף"], featured:true },
    { id:31, name:"Address Beach Resort", nameEn:"The Address Beach Resort", category:"hotels", subcategory:"5star", stars:5, description:"מגדל על חוף JBR עם בריכת overflow מהגבוהות בעולם.", image:"https://images.pexels.com/photos/14750186/pexels-photo-14750186.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,000-5,500 ללילה", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-879-8888", tags:["5 כוכבים","בריכה","JBR"], featured:false },
    { id:32, name:"W Dubai The Palm", nameEn:"W Dubai The Palm", category:"hotels", subcategory:"5star", stars:5, description:"מלון W תוסס על הפאלם עם מסיבות בריכה מפורסמות.", image:"https://images.pexels.com/photos/26838210/pexels-photo-26838210.jpeg", rating:4.4, price:"$$$", priceRange:"₪900-4,500 ללילה", address:"Palm Jumeirah", lat:25.1200, lng:55.1350, phone:"+971-4-245-5555", tags:["5 כוכבים","W","מסיבות"], featured:false },
    { id:33, name:"Ritz-Carlton JBR", nameEn:"The Ritz-Carlton Dubai", category:"hotels", subcategory:"5star", stars:5, description:"ריץ-קרלטון על חוף JBR, מתאים לחופשות משפחה יוקרתיות.", image:"https://images.pexels.com/photos/35155690/pexels-photo-35155690.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,100-6,000 ללילה", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-399-4000", tags:["5 כוכבים","ריץ","משפחות"], featured:false },
    { id:34, name:"Conrad Dubai", nameEn:"Conrad Dubai", category:"hotels", subcategory:"5star", stars:5, description:"עיצוב מודרני ואמנות עכשווית על שייח' זייד רוד.", image:"https://images.pexels.com/photos/34084119/pexels-photo-34084119.jpeg", rating:4.4, price:"$$$", priceRange:"₪700-3,200 ללילה", address:"Sheikh Zayed Road", lat:25.2256, lng:55.2688, phone:"+971-4-444-7444", tags:["5 כוכבים","קונרד","עיצוב"], featured:false },
    { id:35, name:"Grand Hyatt Dubai", nameEn:"Grand Hyatt Dubai", category:"hotels", subcategory:"5star", stars:5, description:"מתחם נופש ענק עם גינות טרופיות ב-37 דונם בלב דובאי.", image:"https://images.pexels.com/photos/34972151/pexels-photo-34972151.jpeg", rating:4.4, price:"$$$", priceRange:"₪750-3,500 ללילה", address:"Oud Metha", lat:25.2200, lng:55.3100, phone:"+971-4-317-1234", tags:["5 כוכבים","היאט","גינות"], featured:false },
    { id:36, name:"Kempinski Mall of Emirates", nameEn:"Kempinski Hotel Mall of the Emirates", category:"hotels", subcategory:"5star", stars:5, description:"מחובר ישירות לקניון האמירויות, עם נוף לשלג של Ski Dubai.", image:"https://images.pexels.com/photos/14750359/pexels-photo-14750359.jpeg", rating:4.5, price:"$$$", priceRange:"₪900-4,000 ללילה", address:"Mall of Emirates", lat:25.1181, lng:55.2005, phone:"+971-4-341-0000", tags:["5 כוכבים","קניון","סקי"], featured:false },
    { id:37, name:"JW Marriott Marquis", nameEn:"JW Marriott Marquis Dubai", category:"hotels", subcategory:"5star", stars:5, description:"המלון הגבוה בעולם עם 72 קומות ו-14 מסעדות.", image:"https://images.pexels.com/photos/14750284/pexels-photo-14750284.jpeg", rating:4.6, price:"$$$", priceRange:"₪700-3,000 ללילה", address:"Business Bay", lat:25.1867, lng:55.2625, phone:"+971-4-414-3000", tags:["5 כוכבים","הגבוה","Business Bay"], featured:true },
    { id:38, name:"Habtoor Grand Resort", nameEn:"Habtoor Grand Resort Autograph", category:"hotels", subcategory:"5star", stars:5, description:"נופש ענק על חוף JBR עם חוף פרטי ומסעדות רבות.", image:"https://images.pexels.com/photos/34972118/pexels-photo-34972118.jpeg", rating:4.3, price:"$$$", priceRange:"₪800-3,800 ללילה", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-399-5000", tags:["5 כוכבים","חוף","JBR"], featured:false },
    { id:39, name:"Le Meridien Airport", nameEn:"Le Meridien Dubai Hotel", category:"hotels", subcategory:"5star", stars:5, description:"קרוב לנמל התעופה עם בריכה ענקית ומרכז כנסים.", image:"https://images.pexels.com/photos/14750466/pexels-photo-14750466.jpeg", rating:4.2, price:"$$", priceRange:"₪600-2,500 ללילה", address:"Airport Road", lat:25.2500, lng:55.3400, phone:"+971-4-702-2455", tags:["5 כוכבים","שדה תעופה","כנסים"], featured:false },
    { id:40, name:"Hyatt Regency Deira", nameEn:"Hyatt Regency Dubai", category:"hotels", subcategory:"5star", stars:5, description:"היאט רג'נסי בדיירה עם גישה לשוק הזהב ונוף לקריק.", image:"https://images.pexels.com/photos/14750191/pexels-photo-14750191.jpeg", rating:4.2, price:"$$", priceRange:"₪600-2,500 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-209-6914", tags:["5 כוכבים","דיירה","קריק"], featured:false },

    // === 3-4 STARS ===
    { id:41, name:"Rove Downtown", nameEn:"Rove Downtown Dubai", category:"hotels", subcategory:"3-4star", stars:4, description:"מלון בוטיק צמוד לדובאי מול ולברג' חליפה, ערך מצוין למיקום.", image:"https://images.pexels.com/photos/10906732/pexels-photo-10906732.jpeg", rating:4.3, price:"$$", priceRange:"₪280-550 ללילה", address:"Downtown Dubai", lat:25.1972, lng:55.2744, phone:"+971-4-561-9999", tags:["3-4 כוכבים","מרכזי","ערך"], featured:true },
    { id:42, name:"Rove City Walk", nameEn:"Rove City Walk", category:"hotels", subcategory:"3-4star", stars:4, description:"מלון עיצובי ורענן באזור City Walk הטרנדי.", image:"https://images.pexels.com/photos/35394616/pexels-photo-35394616.jpeg", rating:4.2, price:"$$", priceRange:"₪260-500 ללילה", address:"City Walk", lat:25.2100, lng:55.2600, phone:"+971-4-561-9888", tags:["3-4 כוכבים","City Walk","עיצובי"], featured:false },
    { id:43, name:"Rove Trade Centre", nameEn:"Rove Trade Centre", category:"hotels", subcategory:"3-4star", stars:3, description:"בין דובאי העתיקה לחדשה, אידאלי לעסקים ותיירות.", image:"https://images.pexels.com/photos/29196946/pexels-photo-29196946.jpeg", rating:4.1, price:"$$", priceRange:"₪230-450 ללילה", address:"Trade Centre", lat:25.2256, lng:55.2688, phone:"+971-4-561-9777", tags:["3-4 כוכבים","מרכזי","עסקים"], featured:false },
    { id:44, name:"Citymax Al Barsha", nameEn:"Citymax Hotel Al Barsha", category:"hotels", subcategory:"3-4star", stars:3, description:"מלון תקציבי נוח בסמוך לקניון האמירויות עם בריכה על הגג.", image:"https://images.pexels.com/photos/34698507/pexels-photo-34698507.jpeg", rating:4.0, price:"$$", priceRange:"₪200-380 ללילה", address:"Al Barsha", lat:25.1181, lng:55.2005, phone:"+971-4-379-1999", tags:["3-4 כוכבים","תקציבי","קניון"], featured:false },
    { id:45, name:"Citymax Bur Dubai", nameEn:"Citymax Hotel Bur Dubai", category:"hotels", subcategory:"3-4star", stars:3, description:"סיטימקס בדובאי ההיסטורית עם בריכת גג, ליד מטרו.", image:"https://images.pexels.com/photos/36794534/pexels-photo-36794534.jpeg", rating:3.9, price:"$", priceRange:"₪180-350 ללילה", address:"Bur Dubai", lat:25.2500, lng:55.2900, phone:"+971-4-397-4000", tags:["3-4 כוכבים","היסטורי","מטרו"], featured:false },
    { id:46, name:"Premier Inn Airport", nameEn:"Premier Inn Dubai Airport", category:"hotels", subcategory:"3-4star", stars:3, description:"מלון אמין ונוח בסמוך לשדה התעופה לטיסות מוקדמות.", image:"https://images.pexels.com/photos/14750357/pexels-photo-14750357.jpeg", rating:4.0, price:"$$", priceRange:"₪200-380 ללילה", address:"Al Garhoud", lat:25.2500, lng:55.3400, phone:"+971-4-885-7888", tags:["3-4 כוכבים","שדה תעופה","נוח"], featured:false },
    { id:47, name:"ibis Al Barsha", nameEn:"ibis Dubai Al Barsha", category:"hotels", subcategory:"3-4star", stars:3, description:"איביס נקי ואמין בלב אל-ברשה, חדרים נוחים במחיר שפוי.", image:"https://images.pexels.com/photos/14749932/pexels-photo-14749932.jpeg", rating:3.8, price:"$", priceRange:"₪150-280 ללילה", address:"Al Barsha", lat:25.1181, lng:55.2005, phone:"+971-4-307-5000", tags:["3-4 כוכבים","איביס","זול"], featured:false },
    { id:48, name:"ibis Deira City Centre", nameEn:"ibis Dubai Deira City Centre", category:"hotels", subcategory:"3-4star", stars:3, description:"איביס קרוב לדיירה סיטי סנטר ותחנת מטרו.", image:"https://images.pexels.com/photos/14915303/pexels-photo-14915303.jpeg", rating:3.7, price:"$", priceRange:"₪140-260 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-295-7100", tags:["3-4 כוכבים","דיירה","מטרו"], featured:false },
    { id:49, name:"Ramada Downtown", nameEn:"Ramada by Wyndham Downtown Dubai", category:"hotels", subcategory:"3-4star", stars:4, description:"רמדה 4 כוכבים ב-Downtown עם נוף לאופק דובאי.", image:"images/hotels/hotel_1.jpeg", rating:4.1, price:"$$", priceRange:"₪350-650 ללילה", address:"Downtown Dubai", lat:25.1972, lng:55.2744, phone:"+971-4-506-0000", tags:["3-4 כוכבים","Downtown","נוף"], featured:false },
    { id:50, name:"Hilton Garden Inn Al Mina", nameEn:"Hilton Garden Inn Dubai Al Mina", category:"hotels", subcategory:"3-4star", stars:4, description:"הילטון גארדן אין עם ספא ובריכה מקורה ליד נמל דובאי.", image:"images/hotels/hotel_2.jpeg", rating:4.2, price:"$$", priceRange:"₪280-520 ללילה", address:"Al Mina, Bur Dubai", lat:25.2550, lng:55.2800, phone:"+971-4-407-1111", tags:["3-4 כוכבים","הילטון","ספא"], featured:false },
    { id:51, name:"Golden Tulip Deira", nameEn:"Golden Tulip Deira Hotel", category:"hotels", subcategory:"3-4star", stars:3, description:"גולדן טוליפ בדיירה עם בריכת גג, מרחק הליכה משוק הזהב.", image:"images/hotels/hotel_3.jpeg", rating:3.8, price:"$", priceRange:"₪180-340 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-267-7700", tags:["3-4 כוכבים","דיירה","שוק הזהב"], featured:false },
    { id:52, name:"Flora Grand Hotel", nameEn:"Flora Grand Hotel", category:"hotels", subcategory:"3-4star", stars:4, description:"4 כוכבים תקציבי פופולרי בדיירה, ידוע בנקיון.", image:"images/hotels/hotel_4.jpeg", rating:4.0, price:"$", priceRange:"₪170-320 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-236-9999", tags:["3-4 כוכבים","נקי","דיירה"], featured:false },
    { id:53, name:"Savoy Park Apartments", nameEn:"Savoy Park Hotel Apartments", category:"hotels", subcategory:"3-4star", stars:3, description:"דירות-מלון עם מטבחון, אידאלי לשהיות ארוכות ומשפחות.", image:"images/hotels/hotel_5.jpeg", rating:3.9, price:"$$", priceRange:"₪200-380 ללילה", address:"Bur Dubai", lat:25.2500, lng:55.2900, phone:"+971-4-359-0000", tags:["3-4 כוכבים","דירות","משפחות"], featured:false },
    { id:54, name:"Arabian Park Hotel", nameEn:"Arabian Park Hotel", category:"hotels", subcategory:"3-4star", stars:3, description:"מלון בסגנון ערבי עדין, שקט ונוח ליד שדה התעופה.", image:"images/hotels/hotel_6.jpeg", rating:3.8, price:"$", priceRange:"₪200-370 ללילה", address:"Al Garhoud", lat:25.2500, lng:55.3400, phone:"+971-4-295-5666", tags:["3-4 כוכבים","ערבי","שדה תעופה"], featured:false },
    { id:55, name:"Capitol Hotel Dubai", nameEn:"Capitol Hotel Dubai", category:"hotels", subcategory:"3-4star", stars:3, description:"תקציבי ותיק במרכז דובאי ליד תחנת מטרו.", image:"images/hotels/hotel_7.jpeg", rating:3.7, price:"$", priceRange:"₪220-400 ללילה", address:"Trade Centre", lat:25.2256, lng:55.2688, phone:"+971-4-345-0000", tags:["3-4 כוכבים","מרכזי","מטרו"], featured:false },
    { id:56, name:"Royal Ascot Hotel", nameEn:"Royal Ascot Hotel", category:"hotels", subcategory:"3-4star", stars:3, description:"סביר ומוערך בבר דובאי, יחס מצוין לכסף.", image:"images/hotels/hotel_8.jpeg", rating:3.8, price:"$", priceRange:"₪190-350 ללילה", address:"Bur Dubai", lat:25.2600, lng:55.2950, phone:"+971-4-352-0900", tags:["3-4 כוכבים","ערך","Bur Dubai"], featured:false },
    { id:57, name:"ibis One Central", nameEn:"ibis One Central Dubai", category:"hotels", subcategory:"3-4star", stars:3, description:"איביס מודרני בשכנות למרכז הסחר העולמי ו-DIFC.", image:"images/hotels/hotel_9.jpeg", rating:3.9, price:"$", priceRange:"₪160-300 ללילה", address:"One Central", lat:25.2256, lng:55.2688, phone:"+971-4-506-1000", tags:["3-4 כוכבים","DIFC","מודרני"], featured:false },
    { id:58, name:"Rove Healthcare City", nameEn:"Rove Healthcare City", category:"hotels", subcategory:"3-4star", stars:3, description:"רוב מינימליסטי ונוח לחובבי מרכז העיר.", image:"images/hotels/hotel_10.jpeg", rating:4.0, price:"$", priceRange:"₪200-400 ללילה", address:"Healthcare City", lat:25.2300, lng:55.3200, phone:"+971-4-561-9666", tags:["3-4 כוכבים","רוב","מינימלי"], featured:false },
    { id:59, name:"Smana Hotel Al Raffa", nameEn:"Smana Hotel Al Raffa", category:"hotels", subcategory:"3-4star", stars:3, description:"מעוצב ומודרני בשכונת אל-רפא ההיסטורית.", image:"images/hotels/hotel_11.jpeg", rating:3.8, price:"$", priceRange:"₪160-300 ללילה", address:"Al Raffa, Bur Dubai", lat:25.2550, lng:55.2850, phone:"+971-4-359-5000", tags:["3-4 כוכבים","מעוצב","היסטורי"], featured:false },
    { id:60, name:"Premier Inn Silicon Oasis", nameEn:"Premier Inn Dubai Silicon Oasis", category:"hotels", subcategory:"3-4star", stars:3, description:"פרמייר אין עם בריכה ושאטל חינם.", image:"images/hotels/hotel_12.jpeg", rating:4.1, price:"$$", priceRange:"₪230-420 ללילה", address:"Silicon Oasis", lat:25.1200, lng:55.3800, phone:"+971-4-501-6000", tags:["3-4 כוכבים","שאטל","בריכה"], featured:false },

    // === BUDGET ===
    { id:61, name:"XVA Art Hotel", nameEn:"XVA Art Hotel", category:"hotels", subcategory:"budget", stars:2, description:"מלון בוטיק אמנותי בשכונה ההיסטורית של אל-פהידי, ייחודי.", image:"images/hotels/hotel_13.jpeg", rating:4.3, price:"$$", priceRange:"₪250-450 ללילה", address:"Al Fahidi, Bur Dubai", lat:25.2633, lng:55.2975, phone:"+971-4-353-5383", tags:["תקציבי","אמנות","היסטורי"], featured:true },
    { id:62, name:"Orient Guest House", nameEn:"Orient Guest House", category:"hotels", subcategory:"budget", stars:2, description:"בית אורחים מסורתי עם חצרות פתוחות מול מוזיאון דובאי.", image:"images/hotels/hotel_14.jpeg", rating:4.1, price:"$", priceRange:"₪180-320 ללילה", address:"Al Fahidi, Bur Dubai", lat:25.2633, lng:55.2975, phone:"+971-4-351-9111", tags:["תקציבי","מסורתי","מוזיאון"], featured:false },
    { id:63, name:"Sheroes Hostel", nameEn:"Sheroes Hostel Business Bay", category:"hotels", subcategory:"budget", stars:1, description:"הוסטל מודרני עם תאי שינה וWiFi מהיר, אידאלי לתקציב נמוך.", image:"images/hotels/hotel_15.jpeg", rating:4.0, price:"$", priceRange:"₪80-180 ללילה", address:"Business Bay", lat:25.1867, lng:55.2625, phone:"+971-4-555-0001", tags:["תקציבי","הוסטל","צעירים"], featured:false },
    { id:64, name:"Somewhere Barsha Heights", nameEn:"Somewhere Hotel Barsha Heights", category:"hotels", subcategory:"budget", stars:3, description:"תקציבי עם בר, גג-ברים ובריכה, ערך מצוין.", image:"images/hotels/hotel_16.jpeg", rating:4.0, price:"$", priceRange:"₪150-280 ללילה", address:"Barsha Heights", lat:25.1000, lng:55.1700, phone:"+971-4-399-3399", tags:["תקציבי","בריכה","גג"], featured:false },
    { id:65, name:"ibis Styles Jumeirah", nameEn:"ibis Styles Dubai Jumeirah", category:"hotels", subcategory:"budget", stars:3, description:"איביס סטיילס צבעוני קרוב לחוף ג'ומיירה.", image:"images/hotels/hotel_17.jpeg", rating:3.9, price:"$", priceRange:"₪160-300 ללילה", address:"Jumeirah", lat:25.2100, lng:55.2500, phone:"+971-4-355-0000", tags:["תקציבי","צבעוני","חוף"], featured:false },
    { id:66, name:"Al Seef Heritage Hotel", nameEn:"Al Seef Heritage Hotel", category:"hotels", subcategory:"budget", stars:3, description:"מלון מורשת בעיצוב ערבי קלאסי על גדות קריק.", image:"images/hotels/hotel_18.jpeg", rating:4.2, price:"$$", priceRange:"₪300-500 ללילה", address:"Al Seef, Dubai Creek", lat:25.2633, lng:55.2975, phone:"+971-4-707-7077", tags:["תקציבי","מורשת","קריק"], featured:true },
    { id:67, name:"Tulip Inn Deira", nameEn:"Tulip Inn Dubai", category:"hotels", subcategory:"budget", stars:2, description:"פשוט ונקי בדיירה, קרוב לשוק הזהב ומטרו.", image:"images/hotels/hotel_19.jpeg", rating:3.5, price:"$", priceRange:"₪130-240 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-229-8000", tags:["תקציבי","דיירה","זול"], featured:false },
    { id:68, name:"Byblos Hotel", nameEn:"Byblos Hotel Dubai", category:"hotels", subcategory:"budget", stars:3, description:"מלון לבנוני עם מסעדה מזרח-תיכונית מצוינת.", image:"images/hotels/hotel_20.jpeg", rating:3.8, price:"$", priceRange:"₪200-380 ללילה", address:"Al Barsha, TECOM", lat:25.1000, lng:55.1700, phone:"+971-4-449-9900", tags:["תקציבי","לבנוני","TECOM"], featured:false },
    { id:69, name:"Sun & Sands Hotel", nameEn:"Sun & Sands Hotel", category:"hotels", subcategory:"budget", stars:2, description:"שמש וחול בדיירה, חדרים פשוטים ליד הנמל.", image:"images/hotels/hotel_21.jpeg", rating:3.4, price:"$", priceRange:"₪110-220 ללילה", address:"Deira, Baniyas", lat:25.2700, lng:55.2900, phone:"+971-4-223-2000", tags:["תקציבי","פשוט","דיירה"], featured:false },
    { id:70, name:"Dubai Youth Hostel", nameEn:"Dubai Youth Hostel", category:"hotels", subcategory:"budget", stars:1, description:"אכסניית הנוער הרשמית של דובאי, עם מעונות ממוזגים.", image:"images/hotels/hotel_22.jpeg", rating:3.6, price:"$", priceRange:"₪60-150 ללילה", address:"Al Qusais", lat:25.2800, lng:55.3800, phone:"+971-4-298-8151", tags:["תקציבי","אכסנייה","צעירים"], featured:false },
    { id:71, name:"Four Points Bur Dubai", nameEn:"Four Points by Sheraton Bur Dubai", category:"hotels", subcategory:"budget", stars:3, description:"Four Points נוח ואמין בבר דובאי עם בריכה.", image:"images/hotels/hotel_23.jpeg", rating:4.0, price:"$$", priceRange:"₪250-450 ללילה", address:"Bur Dubai", lat:25.2600, lng:55.2950, phone:"+971-4-397-7444", tags:["תקציבי","שרתון","בריכה"], featured:false },
    { id:72, name:"President Hotel", nameEn:"President Hotel Dubai", category:"hotels", subcategory:"budget", stars:2, description:"ותיק ואמין בבר דובאי, פופולרי בקרב מטיילים חוזרים.", image:"images/hotels/hotel_24.jpeg", rating:3.6, price:"$", priceRange:"₪150-270 ללילה", address:"Bur Dubai", lat:25.2600, lng:55.2950, phone:"+971-4-334-0000", tags:["תקציבי","ותיק","Bur Dubai"], featured:false },
    { id:73, name:"Hyatt Place Al Rigga", nameEn:"Hyatt Place Dubai Al Rigga", category:"hotels", subcategory:"budget", stars:3, description:"Hyatt Place תקציבי-פרמיום בדיירה עם ארוחת בוקר כלולה.", image:"https://images.pexels.com/photos/31820069/pexels-photo-31820069.jpeg", rating:4.1, price:"$$", priceRange:"₪220-400 ללילה", address:"Al Rigga, Deira", lat:25.2700, lng:55.2900, phone:"+971-4-233-1234", tags:["תקציבי","היאט","בוקר כלול"], featured:false },
    { id:74, name:"Al Ain Palace Hotel", nameEn:"Al Ain Palace Hotel Dubai", category:"hotels", subcategory:"budget", stars:2, description:"ותיק בבר דובאי עם אווירה ערבית, קרוב לבורג'ומן.", image:"https://images.pexels.com/photos/30245006/pexels-photo-30245006.jpeg", rating:3.5, price:"$", priceRange:"₪130-250 ללילה", address:"Bur Dubai", lat:25.2600, lng:55.2950, phone:"+971-4-426-0999", tags:["תקציבי","ערבי","ותיק"], featured:false },
    { id:75, name:"Concorde Deira", nameEn:"Concorde Deira Hotel", category:"hotels", subcategory:"budget", stars:3, description:"שופץ לאחרונה עם בריכת גג, ליד השוקים.", image:"https://images.pexels.com/photos/34596088/pexels-photo-34596088.jpeg", rating:3.7, price:"$", priceRange:"₪130-250 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-227-3000", tags:["תקציבי","משופץ","שוקים"], featured:false },
    { id:76, name:"Millennium Barsha Heights", nameEn:"Millennium Place Barsha Heights", category:"hotels", subcategory:"budget", stars:3, description:"מודרני בברשה הייטס, ידוע בשירות ביחס למחיר.", image:"https://images.pexels.com/photos/14749935/pexels-photo-14749935.jpeg", rating:4.0, price:"$$", priceRange:"₪220-400 ללילה", address:"Barsha Heights", lat:25.1000, lng:55.1700, phone:"+971-4-454-5555", tags:["תקציבי","מילניום","שירות"], featured:false },
    { id:77, name:"Citymax Business Bay", nameEn:"Citymax Hotel Business Bay", category:"hotels", subcategory:"budget", stars:3, description:"סיטימקס טרנדי ב-Business Bay עם בריכה ועיצוב עכשווי.", image:"https://images.pexels.com/photos/14749879/pexels-photo-14749879.jpeg", rating:3.9, price:"$$", priceRange:"₪200-380 ללילה", address:"Business Bay", lat:25.1867, lng:55.2625, phone:"+971-4-379-2000", tags:["תקציבי","Business Bay","בריכה"], featured:false },
    { id:78, name:"Aloft Dubai South", nameEn:"Aloft Dubai South", category:"hotels", subcategory:"budget", stars:3, description:"צעיר ומוזיקלי בדובאי סאות', קרוב לאקספו סיטי.", image:"https://images.pexels.com/photos/31851252/pexels-photo-31851252.jpeg", rating:3.8, price:"$$", priceRange:"₪200-380 ללילה", address:"Dubai South", lat:25.0000, lng:55.1800, phone:"+971-4-248-0000", tags:["תקציבי","Aloft","אקספו"], featured:false },
    { id:79, name:"Signature Al Barsha", nameEn:"Signature Hotel Al Barsha", category:"hotels", subcategory:"budget", stars:3, description:"בוטיק קטן בסגנון עכשווי, ערך טוב לכסף.", image:"https://images.pexels.com/photos/14750186/pexels-photo-14750186.jpeg", rating:3.8, price:"$", priceRange:"₪190-340 ללילה", address:"Al Barsha", lat:25.1181, lng:55.2005, phone:"+971-4-399-5599", tags:["תקציבי","בוטיק","Al Barsha"], featured:false },
    { id:80, name:"Comfort Inn Deira", nameEn:"Comfort Inn Dubai", category:"hotels", subcategory:"budget", stars:2, description:"שירות בסיסי תקין, אפשרות חסכונית לטיולים.", image:"https://images.pexels.com/photos/26838210/pexels-photo-26838210.jpeg", rating:3.4, price:"$", priceRange:"₪120-230 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-205-0000", tags:["תקציבי","בסיסי","זול"], featured:false },
  ],
  restaurants: [
    { id:101, name:"Nobu Dubai", nameEn:"Nobu Dubai", category:"restaurants", subcategory:"ultra-luxury", description:"סניף דובאי של רשת המסעדות היפנית היוקרתית של שף נובו מאצוהיסה.", image:"images/restaurants/rest_1.jpeg", rating:4.8, price:"$$$$", priceRange:"₪400-800 לזוג", address:"Atlantis The Palm", lat:25.1304, lng:55.1171, phone:"+971-4-426-2626", tags:["יוקרתי מאוד","יפני","סושי"], featured:true },
    { id:102, name:"Al Fanar", nameEn:"Al Fanar", category:"restaurants", subcategory:"local", description:"מסעדה אמיראתית מסורתית עם עיצוב ביתי אותנטי.", image:"images/restaurants/rest_2.jpeg", rating:4.5, price:"$$", priceRange:"₪100-250 לזוג", address:"Festival City Mall", lat:25.2243, lng:55.3524, phone:"+971-4-232-9966", tags:["עממי","אמיראתי","מסורתי"], featured:true },
    { id:103, name:"Zuma Dubai", nameEn:"Zuma Dubai", category:"restaurants", subcategory:"ultra-luxury", description:"מסעדה יפנית עכשווית ברמה עולמית. הברנץ' של יום שישי מפורסם.", image:"images/restaurants/rest_3.jpeg", rating:4.7, price:"$$$$", priceRange:"₪500-1,000 לזוג", address:"DIFC, Gate Village", lat:25.2135, lng:55.2825, phone:"+971-4-425-5660", tags:["יוקרתי מאוד","יפני","ברנץ'"], featured:false },
    { id:104, name:"Ravi Restaurant", nameEn:"Ravi Restaurant", category:"restaurants", subcategory:"street", description:"מסעדה פקיסטנית אגדית מ-1978. אוכל מדהים במחירי רצפה - סוד מקומי.", image:"images/restaurants/rest_4.jpeg", rating:4.3, price:"$", priceRange:"₪30-70 לזוג", address:"Satwa", lat:25.2256, lng:55.2688, phone:"+971-4-331-5353", tags:["אוכל רחוב","פקיסטני","זול"], featured:true },
    { id:105, name:"Pierchic", nameEn:"Pierchic", category:"restaurants", subcategory:"luxury", description:"מסעדת פירות ים על רציף מעל הים. נוף מהמם לשקיעה.", image:"images/restaurants/rest_5.jpeg", rating:4.6, price:"$$$$", priceRange:"₪500-900 לזוג", address:"Al Qasr Hotel, Jumeirah", lat:25.1345, lng:55.1842, phone:"+971-4-432-3232", tags:["יוקרתי","פירות ים","שקיעה"], featured:true },
    { id:106, name:"Operation Falafel", nameEn:"Operation Falafel", category:"restaurants", subcategory:"lebanese", description:"רשת מסעדות לבנונית-ערבית עם פלאפל, חומוס ושווארמה ברמה גבוהה.", image:"images/restaurants/rest_6.jpeg", rating:4.2, price:"$", priceRange:"₪40-100 לזוג", address:"סניפים בכל דובאי", lat:25.2048, lng:55.2708, phone:"+971-4-222-2111", tags:["לבנוני","פלאפל","תקציבי"], featured:false },
    { id:107, name:"Oshi", nameEn:"Oshi", category:"restaurants", subcategory:"israeli", description:"מסעדה ישראלית עם תפריט ים תיכוני - חומוס, שקשוקה, סלטים ובשרים על האש.", image:"images/restaurants/rest_7.jpeg", rating:4.4, price:"$$", priceRange:"₪150-350 לזוג", address:"JBR, The Walk", lat:25.0780, lng:55.1340, phone:"+971-4-555-1234", tags:["ישראלי","כשר","ים תיכוני"], featured:true },
    { id:108, name:"Shabestan", nameEn:"Shabestan", category:"restaurants", subcategory:"israeli", description:"מסעדה פרסית-ישראלית עם מנות מזה\"ת אותנטיות ואווירה ביתית.", image:"images/restaurants/rest_8.jpeg", rating:4.3, price:"$$", priceRange:"₪120-300 לזוג", address:"Downtown Dubai", lat:25.2000, lng:55.2740, phone:"+971-4-555-5678", tags:["ישראלי","פרסי","מזה\"ת"], featured:false },
    { id:109, name:"The Kosher Grill", nameEn:"The Kosher Grill", category:"restaurants", subcategory:"israeli", description:"מסעדה כשרה בדובאי עם בשרים, המבורגרים ומנות ישראליות. כשרות מהדרין.", image:"images/restaurants/rest_9.jpeg", rating:4.5, price:"$$$", priceRange:"₪200-500 לזוג", address:"DIFC", lat:25.2135, lng:55.2825, phone:"+971-4-555-9012", tags:["ישראלי","כשר","בשרים"], featured:true },
    { id:110, name:"Al Hallab", nameEn:"Al Hallab", category:"restaurants", subcategory:"lebanese", description:"רשת לבנונית מפורסמת עם מנות מסורתיות, כנאפה מדהימה.", image:"images/restaurants/rest_10.jpeg", rating:4.4, price:"$$", priceRange:"₪80-200 לזוג", address:"Dubai Mall", lat:25.1985, lng:55.2796, phone:"+971-4-339-9090", tags:["לבנוני","כנאפה","קניון"], featured:false },
    { id:111, name:"Bosporus Turkish", nameEn:"Bosporus Turkish Cuisine", category:"restaurants", subcategory:"turkish", description:"מסעדה טורקית אותנטית עם קבאב, לחמג'ון ובקלאווה.", image:"images/restaurants/rest_11.jpeg", rating:4.3, price:"$$", priceRange:"₪100-250 לזוג", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-447-7744", tags:["טורקי","קבאב","אותנטי"], featured:false },
    { id:112, name:"Gunaydin Dubai", nameEn:"Gunaydin", category:"restaurants", subcategory:"turkish", description:"מסעדת בשרים טורקית יוקרתית, מנות סטייק וכבש מרהיבות.", image:"images/restaurants/rest_12.jpeg", rating:4.6, price:"$$$", priceRange:"₪300-600 לזוג", address:"DIFC", lat:25.2135, lng:55.2825, phone:"+971-4-350-7050", tags:["טורקי","סטייק","יוקרתי"], featured:true },
    { id:113, name:"Ossiano", nameEn:"Ossiano", category:"restaurants", subcategory:"ultra-luxury", description:"מסעדת שף מישלן בתוך אקוריום ענק באטלנטיס. חוויה בלתי נשכחת.", image:"images/restaurants/rest_13.jpeg", rating:4.9, price:"$$$$$", priceRange:"₪800-2,000 לזוג", address:"Atlantis The Palm", lat:25.1304, lng:55.1171, phone:"+971-4-426-2626", tags:["יוקרתי מאוד","מישלן","אקוריום"], featured:true },
    { id:114, name:"Al Mallah", nameEn:"Al Mallah", category:"restaurants", subcategory:"street", description:"שווארמה ומנות רחוב ערביות מעולות. מקום מקומי אותנטי.", image:"images/restaurants/rest_14.jpeg", rating:4.1, price:"$", priceRange:"₪20-60 לזוג", address:"Al Dhiyafa St, Satwa", lat:25.2256, lng:55.2688, phone:"+971-4-398-4723", tags:["אוכל רחוב","שווארמה","זול"], featured:false },
    { id:115, name:"La Petite Maison", nameEn:"La Petite Maison", category:"restaurants", subcategory:"luxury", description:"מסעדה צרפתית-ניסואית ברמה עולמית. אחת הטובות בדובאי.", image:"images/restaurants/rest_15.jpeg", rating:4.7, price:"$$$$", priceRange:"₪400-800 לזוג", address:"DIFC", lat:25.2135, lng:55.2825, phone:"+971-4-439-0505", tags:["יוקרתי","צרפתי","DIFC"], featured:false },
    { id:116, name:"Leila", nameEn:"Leila Restaurant", category:"restaurants", subcategory:"lebanese", description:"מסעדה לבנונית יוקרתית עם מזה מסורתי ואווירה רומנטית.", image:"images/restaurants/rest_16.jpeg", rating:4.5, price:"$$$", priceRange:"₪200-400 לזוג", address:"Madinat Jumeirah", lat:25.1345, lng:55.1842, phone:"+971-4-432-3232", tags:["לבנוני","רומנטי","מזה"], featured:false },
    { id:117, name:"Karak House", nameEn:"Karak House", category:"restaurants", subcategory:"street", description:"צ'אי קארק (תה הודי) ומנות רחוב הודיות. המקום הכי אותנטי.", image:"images/restaurants/rest_17.jpeg", rating:4.0, price:"$", priceRange:"₪10-40 לזוג", address:"סניפים בכל דובאי", lat:25.2048, lng:55.2708, phone:"", tags:["אוכל רחוב","תה","הודי"], featured:false },
    { id:118, name:"Tresind Studio", nameEn:"Tresind Studio", category:"restaurants", subcategory:"ultra-luxury", description:"מסעדת שף הודית עם 2 כוכבי מישלן. חוויית טעימות בלתי נשכחת.", image:"images/restaurants/rest_18.jpeg", rating:4.9, price:"$$$$$", priceRange:"₪1,000-2,000 לזוג", address:"DIFC", lat:25.2135, lng:55.2825, phone:"+971-4-439-0808", tags:["יוקרתי מאוד","מישלן","הודי"], featured:false },
  ],
  attractions: [
    { id:201, name:"ברג' חליפה", nameEn:"Burj Khalifa", category:"attractions", subcategory:"landmark", description:"הבניין הגבוה בעולם (828 מטר). תצפית בקומה 148 עם נוף עוצר נשימה.", image:"images/hotels/hotel_13.jpeg", rating:4.9, price:"$$", priceRange:"₪149-399 / $40-109", address:"Downtown Dubai", lat:25.1972, lng:55.2744, phone:"+971-4-888-8888", tags:["תצפית","סמל","חובה"], webcam:"https://www.webcamtaxi.com/en/united-arab-emirates/dubai/burj-khalifa-lake-dubai.html", featured:true },
    { id:202, name:"Dubai Mall", nameEn:"Dubai Mall", category:"attractions", subcategory:"shopping", description:"הקניון הגדול בעולם עם מעל 1,200 חנויות, אקוריום ומשטח החלקה.", image:"images/hotels/hotel_14.jpeg", rating:4.7, price:"חינם", priceRange:"כניסה חינם", address:"Downtown Dubai", lat:25.1985, lng:55.2796, phone:"+971-4-362-7500", tags:["קניות","משפחות","חינם"], webcam:"https://www.webcamtaxi.com/en/united-arab-emirates/dubai/burj-khalifa-lake-dubai.html", featured:true },
    { id:203, name:"Palm Jumeirah", nameEn:"Palm Jumeirah", category:"attractions", subcategory:"landmark", description:"האי המלאכותי בצורת דקל. חופים, מלונות יוקרה ומונורייל.", image:"images/hotels/hotel_15.jpeg", rating:4.6, price:"$", priceRange:"₪25 / $7 מונורייל", address:"Palm Jumeirah", lat:25.1124, lng:55.1390, phone:"", tags:["אי","חוף","מונורייל"], webcam:"https://www.skylinewebcams.com/en/webcam/united-arab-emirates/dubai/dubai/dubai-marina.html", featured:true },
    { id:204, name:"Dubai Frame", nameEn:"Dubai Frame", category:"attractions", subcategory:"landmark", description:"מסגרת זהב ענקית בגובה 150 מטר. תצפית 360.", image:"images/hotels/hotel_16.jpeg", rating:4.5, price:"$", priceRange:"₪50 / $14", address:"Zabeel Park", lat:25.2346, lng:55.3005, phone:"+971-4-354-6666", tags:["תצפית","צילום","חדש"], featured:false },
    { id:205, name:"מוזיאון העתיד", nameEn:"Museum of the Future", category:"attractions", subcategory:"museum", description:"אחד הבניינים היפים בעולם עם תערוכות על טכנולוגיות העתיד.", image:"images/hotels/hotel_17.jpeg", rating:4.8, price:"$$", priceRange:"₪149 / $40", address:"Sheikh Zayed Road", lat:25.2196, lng:55.2806, phone:"+971-4-554-0049", tags:["מוזיאון","טכנולוגיה","ארכיטקטורה"], featured:true },
    { id:206, name:"ספארי מדבר", nameEn:"Desert Safari", category:"attractions", subcategory:"adventure", description:"נסיעת שטח בדיונות, רכיבה על גמלים, BBQ בדואי וריקודי בטן.", image:"images/hotels/hotel_22.jpeg", rating:4.7, price:"$$", priceRange:"₪150-350 / $40-95", address:"Dubai Desert", lat:25.0500, lng:55.4000, phone:"", tags:["מדבר","הרפתקה","שקיעה"], featured:true },
  ],
  shopping: [
    { id:301, name:"Dubai Mall", nameEn:"Dubai Mall", category:"shopping", subcategory:"mall", description:"הקניון הגדול בעולם! מעל 1,200 חנויות, אקוריום, החלקה על קרח.", image:"images/shopping/shop_1.jpeg", rating:4.8, price:"$-$$$$$", priceRange:"כל טווח מחירים", address:"Downtown Dubai", lat:25.1985, lng:55.2796, tags:["קניון","יוקרה","משפחות"], featured:true },
    { id:302, name:"Gold Souk", nameEn:"Gold Souk", category:"shopping", subcategory:"souk", description:"שוק הזהב המפורסם. מאות חנויות תכשיטים במחירים תחרותיים.", image:"images/shopping/shop_2.jpeg", rating:4.5, price:"$$-$$$$", priceRange:"תלוי בקנייה", address:"Deira", lat:25.2867, lng:55.2968, tags:["זהב","תכשיטים","מסורתי"], featured:true },
    { id:303, name:"Mall of the Emirates", nameEn:"Mall of the Emirates", category:"shopping", subcategory:"mall", description:"קניון ענק עם Ski Dubai - מתחם סקי מקורה בלב המדבר!", image:"images/shopping/shop_3.jpeg", rating:4.6, price:"$$-$$$$", priceRange:"כל טווח מחירים", address:"Sheikh Zayed Road", lat:25.1181, lng:55.2005, tags:["קניון","סקי","בידור"], featured:true },
    { id:304, name:"Spice Souk", nameEn:"Spice Souk", category:"shopping", subcategory:"souk", description:"שוק התבלינים ההיסטורי. ריחות מדהימים ותבלינים מכל העולם.", image:"images/shopping/shop_4.jpeg", rating:4.3, price:"$", priceRange:"זול מאוד", address:"Deira", lat:25.2696, lng:55.2988, tags:["תבלינים","מסורתי","שוק"], featured:false },
  ],
  nightlife: [
    { id:401, name:"White Dubai", nameEn:"White Dubai", category:"nightlife", subcategory:"club", description:"אחד המועדונים הכי מפורסמים בדובאי. DJ-ים בינלאומיים.", image:"images/nightlife/night_1.jpeg", rating:4.5, price:"$$$", priceRange:"₪200-500 / $55-136", address:"Meydan Racecourse", lat:25.1665, lng:55.3052, tags:["מועדון","DJ","לילה"], featured:true },
    { id:402, name:"Atmosphere Lounge", nameEn:"Atmosphere Lounge", category:"nightlife", subcategory:"lounge", description:"בר בקומה 122 של ברג' חליפה. קוקטיילים בגובה.", image:"images/nightlife/night_2.jpeg", rating:4.7, price:"$$$$", priceRange:"₪300-700 / $82-190", address:"Burj Khalifa, Floor 122", lat:25.1972, lng:55.2744, tags:["בר","תצפית","יוקרה"], featured:true },
    { id:403, name:"Ain Dubai", nameEn:"Ain Dubai", category:"nightlife", subcategory:"entertainment", description:"הגלגל הענק הגבוה בעולם (250 מטר).", image:"images/nightlife/night_3.jpeg", rating:4.6, price:"$$", priceRange:"₪130-500 / $35-136", address:"Bluewaters Island", lat:25.0797, lng:55.1193, tags:["גלגל ענק","תצפית","רומנטי"], featured:true },
    { id:404, name:"La Perle Show", nameEn:"La Perle by Dragone", category:"nightlife", subcategory:"show", description:"מופע אקרובטי מרהיב עם אפקטים של מים ואש.", image:"images/nightlife/night_4.jpeg", rating:4.8, price:"$$$", priceRange:"₪300-700 / $82-190", address:"Al Habtoor City", lat:25.1850, lng:55.2448, tags:["מופע","אקרובטיקה","משפחות"], featured:true },
  ],
  transport: [
    { id:501, name:"מטרו דובאי", nameEn:"Dubai Metro", category:"transport", subcategory:"metro", description:"רשת מטרו אוטומטית. הקו האדום והירוק מכסים את רוב נקודות העניין. קנו Nol Card!", image:"https://images.pexels.com/photos/33354945/pexels-photo-33354945.jpeg", rating:4.4, price:"$", priceRange:"₪3-8.5 / $1-2.3 לנסיעה", address:"תחנות בכל דובאי", lat:25.2048, lng:55.2708, tags:["מטרו","זול","נוח"], featured:true },
    { id:502, name:"מוניות דובאי", nameEn:"Dubai Taxi RTA", category:"transport", subcategory:"taxi", description:"מוניות רשמיות בצבע קרם. אמינות ונוחות.", image:"https://images.pexels.com/photos/31747298/pexels-photo-31747298.jpeg", rating:4.2, price:"$$", priceRange:"₪12 בסיס + ₪2/ק\"מ", address:"בכל מקום", lat:25.2048, lng:55.2708, tags:["מונית","נוח","24/7"], featured:false },
    { id:503, name:"Water Taxi / Abra", nameEn:"Water Taxi Abra", category:"transport", subcategory:"boat", description:"סירות עץ מסורתיות חוצות את Dubai Creek ב-1 דירהם!", image:"https://images.pexels.com/photos/31084537/pexels-photo-31084537.jpeg", rating:4.6, price:"$", priceRange:"₪1 / $0.27 לנסיעה", address:"Dubai Creek", lat:25.2633, lng:55.2975, tags:["סירה","מסורתי","זול"], featured:true },
    { id:504, name:"Careem / Uber", nameEn:"Careem Uber", category:"transport", subcategory:"app", description:"שירותי הסעות באפליקציה. Careem הוא המקומי הפופולרי.", image:"https://images.pexels.com/photos/29352929/pexels-photo-29352929.jpeg", rating:4.3, price:"$$", priceRange:"₪15-100 / $4-27 לנסיעה", address:"בכל מקום", lat:25.2048, lng:55.2708, tags:["אפליקציה","נוח","מהיר"], featured:false },
  ],
  casino: [
    { id:601, name:"Wynn Resort Dubai", nameEn:"Wynn Resort Dubai", category:"casino", subcategory:"casino", description:"נפתח בקרוב! ריזורט קזינו ראשון בדובאי.", image:"https://images.pexels.com/photos/31824217/pexels-photo-31824217.jpeg", rating:0, price:"$$$$", priceRange:"טרם פורסם", address:"Ras Al Khaimah", lat:25.1500, lng:55.2000, tags:["קזינו","חדש","יוקרה"], featured:true },
    { id:602, name:"Hippodrome - Meydan", nameEn:"Meydan Racecourse", category:"casino", subcategory:"racing", description:"מתחם מרוצי הסוסים היוקרתי. אירועי הימורים ו-VIP.", image:"https://images.pexels.com/photos/32696882/pexels-photo-32696882.jpeg", rating:4.4, price:"$$$", priceRange:"₪100-500 / $27-136", address:"Meydan", lat:25.1665, lng:55.3052, tags:["מרוצים","הימורים","VIP"], featured:true },
  ]
};

const PRACTICAL_INFO = {
  emergency: { police:"999", ambulance:"998", fire:"997", tourist_police:"+971-800-2438" },
  currency: { name:"דירהם (AED)", rate:"1 ₪ ≈ 1 AED | 1$ ≈ 3.67 AED", tip:"טיפ 10-15% מקובל" },
  visa: "ישראלים מקבלים ויזה אוטומטית בכניסה (30 יום). דרכון בתוקף ל-6 חודשים.",
  weather: "חודשים מומלצים: נובמבר-מרץ (20-30°C). הקיץ חם מאוד (40-50°C).",
  phrases: [
    { he:"שלום", ar:"سلام / مرحبا", pron:"סאלאם / מרחבא" },
    { he:"תודה", ar:"شكراً", pron:"שוכראן" },
    { he:"כמה זה עולה?", ar:"بكم هذا؟", pron:"בכם האד'א?" },
    { he:"כן / לא", ar:"نعم / لا", pron:"נעם / לא" },
    { he:"סליחה", ar:"عفواً", pron:"עפוואן" },
    { he:"אני רוצה...", ar:"أريد...", pron:"אוריד..." },
    { he:"איפה..?", ar:"أين..؟", pron:"אין..?" },
    { he:"יופי / מצוין", ar:"ممتاز", pron:"מומתאז" },
  ],
  tips: [
    "הלבוש: לבוש צנוע במקומות ציבוריים. בחוף ובבריכה - רגיל.",
    "אלכוהול: מותר רק בברים ומסעדות מורשות. אסור ברחוב.",
    "צילום: אסור לצלם אנשים מקומיים ללא רשות.",
    "רמדאן: נא להימנע מאכילה ושתייה ברחוב בשעות הצום.",
    "Nol Card: קנו בשדה התעופה - עובד על מטרו, אוטובוסים ומוניות מים.",
    "שבת: הכל פתוח 7 ימים בשבוע.",
    "כשרות: יש מספר מסעדות כשרות בדובאי.",
  ]
};

const DB_VERSION = 9;
function getDB() {
  const ver = localStorage.getItem(DB_KEY + '_ver');
  if (ver && Number(ver) >= DB_VERSION) {
    const stored = localStorage.getItem(DB_KEY);
    if (stored) return JSON.parse(stored);
  }
  localStorage.setItem(DB_KEY, JSON.stringify(DEFAULT_DATA));
  localStorage.setItem(DB_KEY + '_ver', DB_VERSION);
  return { ...DEFAULT_DATA };
}

function saveDB(data) {
  localStorage.setItem(DB_KEY, JSON.stringify(data));
}

function getAllItems(category) {
  return getDB()[category] || [];
}

function getItem(category, id) {
  return getAllItems(category).find(item => item.id === Number(id));
}

function addItem(category, item) {
  const db = getDB();
  if (!db[category]) db[category] = [];
  item.id = Date.now();
  db[category].push(item);
  saveDB(db);
  return item;
}

function updateItem(category, id, updates) {
  const db = getDB();
  const idx = db[category].findIndex(item => item.id === Number(id));
  if (idx >= 0) {
    db[category][idx] = { ...db[category][idx], ...updates };
    saveDB(db);
    return db[category][idx];
  }
  return null;
}

function deleteItem(category, id) {
  const db = getDB();
  db[category] = db[category].filter(item => item.id !== Number(id));
  saveDB(db);
}

function getFeatured() {
  const db = getDB();
  const all = [];
  for (const cat of Object.keys(db)) {
    all.push(...db[cat].filter(i => i.featured));
  }
  return all;
}

function searchAll(query) {
  const db = getDB();
  const q = query.toLowerCase();
  const results = [];
  for (const cat of Object.keys(db)) {
    results.push(...db[cat].filter(i =>
      i.name?.toLowerCase().includes(q) ||
      i.nameEn?.toLowerCase().includes(q) ||
      i.description?.toLowerCase().includes(q) ||
      i.tags?.some(t => t.includes(q))
    ));
  }
  return results;
}

function getStats() {
  const db = getDB();
  return {
    hotels: db.hotels?.length || 0,
    restaurants: db.restaurants?.length || 0,
    attractions: db.attractions?.length || 0,
    shopping: db.shopping?.length || 0,
    nightlife: db.nightlife?.length || 0,
    transport: db.transport?.length || 0,
    casino: db.casino?.length || 0,
    total: Object.values(db).reduce((sum, arr) => sum + arr.length, 0)
  };
}
