// ===== DATABASE (localStorage) =====
const DB_KEY = 'dubai_guide_db';

const DEFAULT_DATA = {
  hotels: [
    // === 7 STARS / ULTRA LUXURY ===
    { id:1, name:"Burj Al Arab", nameEn:"Burj Al Arab Jumeirah", category:"hotels", subcategory:"7star", stars:7, description:"המלון הסמלי ביותר בדובאי בצורת מפרש, עם שירות 24/7 ייחודי וסוויטות דו-קומתיות.", image:"images/hotels/1.jpg", rating:4.9, price:"$$$$$", priceRange:"₪4,000-25,000 ללילה", address:"Jumeirah Beach Road", lat:25.1412, lng:55.1855, phone:"+971-4-301-7777", tags:["7 כוכבים","מפרש","אייקוני"], featured:true },
    { id:2, name:"Atlantis The Royal", nameEn:"Atlantis The Royal", category:"hotels", subcategory:"7star", stars:7, description:"מלון חדש ומרהיב על הפאלם עם 17 מסעדות ובריכות ספקטקולריות.", image:"images/hotels/2.jpg", rating:4.8, price:"$$$$$", priceRange:"₪2,000-40,000 ללילה", address:"Palm Jumeirah", lat:25.1304, lng:55.1171, phone:"+971-4-426-2000", tags:["7 כוכבים","פאלם","חדש"], featured:true },
    { id:3, name:"Armani Hotel Dubai", nameEn:"Armani Hotel Dubai", category:"hotels", subcategory:"7star", stars:7, description:"בתוך ברג' חליפה, מעוצב אישית על ידי ג'ורג'יו ארמאני.", image:"images/hotels/hotel_3.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪2,500-15,000 ללילה", address:"Burj Khalifa, Downtown", lat:25.1972, lng:55.2744, phone:"+971-4-888-3888", tags:["7 כוכבים","ארמאני","עיצוב"], featured:true },
    { id:4, name:"Bvlgari Resort Dubai", nameEn:"Bvlgari Resort Dubai", category:"hotels", subcategory:"7star", stars:7, description:"מלון בלעדי על אי פרטי בצורת סוס ים, מעוצב במותג בולגרי.", image:"images/hotels/hotel_4.jpeg", rating:4.9, price:"$$$$$", priceRange:"₪2,200-90,000 ללילה", address:"Jumeirah Bay Island", lat:25.2050, lng:55.2350, phone:"+971-4-777-5555", tags:["7 כוכבים","אי פרטי","בולגרי"], featured:true },
    { id:5, name:"The Lana - Dorchester", nameEn:"The Lana Dorchester Collection", category:"hotels", subcategory:"7star", stars:7, description:"חבר בשרשרת דורצ'סטר, עם נוף מרהיב לתעלת דובאי.", image:"images/hotels/hotel_5.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪3,400-92,000 ללילה", address:"Business Bay", lat:25.1867, lng:55.2625, phone:"+971-4-220-0000", tags:["7 כוכבים","דורצ'סטר","חדש"], featured:false },
    { id:6, name:"One&Only The Palm", nameEn:"One&Only The Palm", category:"hotels", subcategory:"7star", stars:7, description:"מלון בוטיק אינטימי על הפאלם עם גינות ים תיכוניות ושירות יוצא דופן.", image:"images/hotels/hotel_6.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪2,600-18,000 ללילה", address:"Palm Jumeirah", lat:25.1150, lng:55.1380, phone:"+971-4-440-1010", tags:["7 כוכבים","בוטיק","פאלם"], featured:false },
    { id:7, name:"One&Only Royal Mirage", nameEn:"One&Only Royal Mirage", category:"hotels", subcategory:"7star", stars:7, description:"קסר ערבי אגדי על חוף הים עם גני דקלים ואווירה רומנטית.", image:"images/hotels/hotel_7.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪1,600-12,000 ללילה", address:"King Salman St, Jumeirah", lat:25.0940, lng:55.1500, phone:"+971-4-399-9999", tags:["7 כוכבים","ארמון","רומנטי"], featured:false },
    { id:8, name:"Four Seasons Jumeirah", nameEn:"Four Seasons Resort Dubai Jumeirah Beach", category:"hotels", subcategory:"7star", stars:7, description:"נופש על 270 מ' של חוף טבעי עם חדרים בגווני פסטל.", image:"images/hotels/hotel_8.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪2,000-14,000 ללילה", address:"Jumeirah Beach", lat:25.2100, lng:55.2500, phone:"+971-4-270-7777", tags:["7 כוכבים","חוף","פור סיזנס"], featured:false },
    { id:9, name:"Four Seasons DIFC", nameEn:"Four Seasons Hotel DIFC", category:"hotels", subcategory:"7star", stars:7, description:"מלון עירוני במרכז הפיננסי עם אמנות עכשווית ומסעדות מדהימות.", image:"images/hotels/hotel_9.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪1,800-10,000 ללילה", address:"DIFC", lat:25.2135, lng:55.2825, phone:"+971-4-506-0000", tags:["7 כוכבים","עסקים","DIFC"], featured:false },
    { id:10, name:"Palazzo Versace", nameEn:"Palazzo Versace Dubai", category:"hotels", subcategory:"7star", stars:7, description:"ארמון איטלקי על גדות דובאי קריק, כל ריהוטו תוכנן על ידי וורסאצ'ה.", image:"images/hotels/hotel_10.jpeg", rating:4.6, price:"$$$$$", priceRange:"₪1,500-10,000 ללילה", address:"Al Jaddaf", lat:25.2243, lng:55.3524, phone:"+971-4-556-8888", tags:["7 כוכבים","וורסאצ'ה","ארמון"], featured:false },
    { id:11, name:"Jumeirah Al Qasr", nameEn:"Jumeirah Al Qasr", category:"hotels", subcategory:"7star", stars:7, description:"ארמון הים של מתחם מדינת ג'ומיירה עם תעלות מים.", image:"images/hotels/hotel_11.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪1,800-15,000 ללילה", address:"Madinat Jumeirah", lat:25.1345, lng:55.1842, phone:"+971-4-366-8888", tags:["7 כוכבים","ארמון","ג'ומיירה"], featured:false },
    { id:12, name:"Jumeirah Marsa Al Arab", nameEn:"Jumeirah Marsa Al Arab", category:"hotels", subcategory:"7star", stars:7, description:"ב-50 המלונות הטובים בעולם 2025, עם עיצוב ימי מדהים.", image:"images/hotels/hotel_12.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪2,500-20,000 ללילה", address:"Umm Suqeim 3", lat:25.1400, lng:55.1860, phone:"+971-4-366-7777", tags:["7 כוכבים","חדש","ימי"], featured:false },
    { id:13, name:"Waldorf Astoria Palm", nameEn:"Waldorf Astoria Dubai Palm Jumeirah", category:"hotels", subcategory:"7star", stars:7, description:"וולדורף-אסטוריה על חוף הפאלם עם מסעדת שף מישלן.", image:"images/hotels/hotel_13.jpeg", rating:4.7, price:"$$$$$", priceRange:"₪1,500-9,000 ללילה", address:"Palm Jumeirah", lat:25.1200, lng:55.1300, phone:"+971-4-818-2222", tags:["7 כוכבים","וולדורף","חוף"], featured:false },
    { id:14, name:"FIVE Palm Jumeirah", nameEn:"FIVE Palm Jumeirah", category:"hotels", subcategory:"7star", stars:7, description:"מלון בוטיק-מסיבות עם מסיבות הגג המפורסמות ביותר בדובאי.", image:"images/hotels/hotel_14.jpeg", rating:4.5, price:"$$$$", priceRange:"₪1,200-7,000 ללילה", address:"Palm Jumeirah West", lat:25.1180, lng:55.1250, phone:"+971-4-455-9999", tags:["7 כוכבים","מסיבות","גג"], featured:false },
    { id:15, name:"Atlantis The Palm", nameEn:"Atlantis The Palm", category:"hotels", subcategory:"7star", stars:7, description:"המלון המקורי על הפאלם עם פארק מים Aquaventure ואקוריום.", image:"images/hotels/15.jpg", rating:4.7, price:"$$$$", priceRange:"₪1,000-12,000 ללילה", address:"Palm Jumeirah", lat:25.1304, lng:55.1171, phone:"+971-4-426-2000", tags:["7 כוכבים","פארק מים","משפחות"], featured:true },
    { id:16, name:"Address Downtown", nameEn:"Address Downtown Dubai", category:"hotels", subcategory:"7star", stars:7, description:"מגדל זהב מעל מזרקת דובאי, נוף מפורסם לברג' חליפה.", image:"images/hotels/16.jpg", rating:4.6, price:"$$$$", priceRange:"₪1,200-8,000 ללילה", address:"Downtown Dubai", lat:25.1972, lng:55.2744, phone:"+971-4-436-8888", tags:["7 כוכבים","Downtown","מזרקה"], featured:false },
    { id:17, name:"St. Regis The Palm", nameEn:"The St. Regis Dubai The Palm", category:"hotels", subcategory:"7star", stars:7, description:"שירות Bespoke אישי ומסעדה של Heston Blumenthal.", image:"images/hotels/hotel_17.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,400-9,000 ללילה", address:"Palm Jumeirah", lat:25.1250, lng:55.1350, phone:"+971-4-218-0000", tags:["7 כוכבים","St.Regis","פאלם"], featured:false },
    { id:18, name:"FIVE Jumeirah Village", nameEn:"FIVE Jumeirah Village", category:"hotels", subcategory:"7star", stars:7, description:"מגדל עם 5 בריכות ואחד ממועדוני הגג הפופולריים.", image:"images/hotels/hotel_18.jpeg", rating:4.4, price:"$$$", priceRange:"₪900-5,000 ללילה", address:"JVC", lat:25.0650, lng:55.2100, phone:"+971-4-455-5555", tags:["7 כוכבים","בריכות","גג"], featured:false },
    { id:19, name:"Raffles The Palm", nameEn:"Raffles The Palm Dubai", category:"hotels", subcategory:"7star", stars:7, description:"רפאלס על הפאלם עם ספא עולמי ואחת הבריכות הגדולות בדובאי.", image:"images/hotels/hotel_19.jpeg", rating:4.7, price:"$$$$", priceRange:"₪1,300-8,500 ללילה", address:"Palm Jumeirah West", lat:25.1220, lng:55.1280, phone:"+971-4-248-8888", tags:["7 כוכבים","רפאלס","ספא"], featured:false },
    { id:20, name:"Jumeirah Al Naseem", nameEn:"Jumeirah Al Naseem", category:"hotels", subcategory:"7star", stars:7, description:"חלק ממתחם מדינת ג'ומיירה עם חוף פרטי וגן חיות ים.", image:"images/hotels/hotel_20.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,400-8,000 ללילה", address:"Madinat Jumeirah", lat:25.1350, lng:55.1850, phone:"+971-4-366-9999", tags:["7 כוכבים","חוף","ג'ומיירה"], featured:false },

    // === 5 STARS ===
    { id:21, name:"Sofitel The Palm", nameEn:"Sofitel Dubai The Palm", category:"hotels", subcategory:"5star", stars:5, description:"אתר נופש צרפתי-ערבי מפואר על הפאלם עם גינות טרופיות.", image:"images/hotels/hotel_21.jpeg", rating:4.5, price:"$$$", priceRange:"₪900-4,000 ללילה", address:"Palm Jumeirah East", lat:25.1280, lng:55.1450, phone:"+971-4-455-6677", tags:["5 כוכבים","צרפתי","פאלם"], featured:true },
    { id:22, name:"Sofitel JBR", nameEn:"Sofitel Dubai Jumeirah Beach", category:"hotels", subcategory:"5star", stars:5, description:"מלון סופיטל על חוף JBR עם מסעדה צרפתית מצוינת.", image:"images/hotels/hotel_22.jpeg", rating:4.4, price:"$$$", priceRange:"₪800-3,500 ללילה", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-448-4848", tags:["5 כוכבים","JBR","חוף"], featured:false },
    { id:23, name:"Fairmont The Palm", nameEn:"Fairmont The Palm", category:"hotels", subcategory:"5star", stars:5, description:"מלון פיירמונט מפואר עם חוף פרטי וספא עולמי.", image:"images/hotels/23.jpg", rating:4.5, price:"$$$", priceRange:"₪850-4,500 ללילה", address:"Palm Jumeirah", lat:25.1260, lng:55.1400, phone:"+971-4-457-3388", tags:["5 כוכבים","פיירמונט","חוף"], featured:false },
    { id:24, name:"Fairmont Dubai", nameEn:"Fairmont Dubai", category:"hotels", subcategory:"5star", stars:5, description:"מלון דגל בלב מרכז דובאי מול מרכז הסחר העולמי.", image:"images/hotels/hotel_24.jpeg", rating:4.4, price:"$$$", priceRange:"₪700-3,500 ללילה", address:"Sheikh Zayed Road", lat:25.2256, lng:55.2688, phone:"+971-4-332-5555", tags:["5 כוכבים","מרכזי","עסקים"], featured:false },
    { id:25, name:"Raffles Dubai", nameEn:"Raffles Dubai", category:"hotels", subcategory:"5star", stars:5, description:"פירמידת רפאלס ליד וואפי סיטי עם גינת גג מרהיבה.", image:"https://images.pexels.com/photos/31820069/pexels-photo-31820069.jpeg", rating:4.6, price:"$$$", priceRange:"₪900-4,500 ללילה", address:"Wafi City, Oud Metha", lat:25.2200, lng:55.3200, phone:"+971-4-324-8888", tags:["5 כוכבים","פירמידה","רפאלס"], featured:false },
    { id:26, name:"Sheraton Grand Dubai", nameEn:"Sheraton Grand Hotel Dubai", category:"hotels", subcategory:"5star", stars:5, description:"שרתון פרמיום על שייח' זייד רוד עם נוף פנורמי ובריכה על הגג.", image:"https://images.pexels.com/photos/30245006/pexels-photo-30245006.jpeg", rating:4.3, price:"$$$", priceRange:"₪650-2,800 ללילה", address:"Sheikh Zayed Road", lat:25.2150, lng:55.2780, phone:"+971-4-507-6666", tags:["5 כוכבים","שרתון","נוף"], featured:false },
    { id:27, name:"Westin Mina Seyahi", nameEn:"Westin Dubai Mina Seyahi", category:"hotels", subcategory:"5star", stars:5, description:"מלון וסטין על חוף הים עם חוף פרטי וגישה ל-Marina.", image:"https://images.pexels.com/photos/34596088/pexels-photo-34596088.jpeg", rating:4.4, price:"$$$", priceRange:"₪700-3,000 ללילה", address:"Dubai Marina", lat:25.0900, lng:55.1500, phone:"+971-4-399-4141", tags:["5 כוכבים","חוף","מרינה"], featured:false },
    { id:28, name:"Hilton Al Habtoor", nameEn:"Hilton Dubai Al Habtoor City", category:"hotels", subcategory:"5star", stars:5, description:"חלק ממתחם Al Habtoor City עם מופעי לה סירק.", image:"https://images.pexels.com/photos/14749935/pexels-photo-14749935.jpeg", rating:4.3, price:"$$$", priceRange:"₪700-3,200 ללילה", address:"Al Habtoor City", lat:25.1850, lng:55.2448, phone:"+971-4-435-5555", tags:["5 כוכבים","הילטון","בידור"], featured:false },
    { id:29, name:"InterContinental Festival", nameEn:"InterContinental Dubai Festival City", category:"hotels", subcategory:"5star", stars:5, description:"מלון על קו המים של דובאי קריק עם נוף לברג' חליפה.", image:"images/hotels/29.jpg", rating:4.5, price:"$$$", priceRange:"₪750-3,500 ללילה", address:"Festival City", lat:25.2243, lng:55.3524, phone:"+971-4-701-1111", tags:["5 כוכבים","קריק","נוף"], featured:false },
    { id:30, name:"Jumeirah Beach Hotel", nameEn:"Jumeirah Beach Hotel", category:"hotels", subcategory:"5star", stars:5, description:"מלון הגלים האייקוני עם נוף לברג' אל-ערב ו-19 מסעדות.", image:"images/hotels/30.jpg", rating:4.5, price:"$$$", priceRange:"₪800-4,000 ללילה", address:"Jumeirah Beach Road", lat:25.1412, lng:55.1855, phone:"+971-4-348-0000", tags:["5 כוכבים","גלים","חוף"], featured:true },
    { id:31, name:"Address Beach Resort", nameEn:"The Address Beach Resort", category:"hotels", subcategory:"5star", stars:5, description:"מגדל על חוף JBR עם בריכת overflow מהגבוהות בעולם.", image:"https://images.pexels.com/photos/14750186/pexels-photo-14750186.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,000-5,500 ללילה", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-879-8888", tags:["5 כוכבים","בריכה","JBR"], featured:false },
    { id:32, name:"W Dubai The Palm", nameEn:"W Dubai The Palm", category:"hotels", subcategory:"5star", stars:5, description:"מלון W תוסס על הפאלם עם מסיבות בריכה מפורסמות.", image:"https://images.pexels.com/photos/26838210/pexels-photo-26838210.jpeg", rating:4.4, price:"$$$", priceRange:"₪900-4,500 ללילה", address:"Palm Jumeirah", lat:25.1200, lng:55.1350, phone:"+971-4-245-5555", tags:["5 כוכבים","W","מסיבות"], featured:false },
    { id:33, name:"Ritz-Carlton JBR", nameEn:"The Ritz-Carlton Dubai", category:"hotels", subcategory:"5star", stars:5, description:"ריץ-קרלטון על חוף JBR, מתאים לחופשות משפחה יוקרתיות.", image:"https://images.pexels.com/photos/35155690/pexels-photo-35155690.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,100-6,000 ללילה", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-399-4000", tags:["5 כוכבים","ריץ","משפחות"], featured:false },
    { id:34, name:"Conrad Dubai", nameEn:"Conrad Dubai", category:"hotels", subcategory:"5star", stars:5, description:"עיצוב מודרני ואמנות עכשווית על שייח' זייד רוד.", image:"images/hotels/34.jpg", rating:4.4, price:"$$$", priceRange:"₪700-3,200 ללילה", address:"Sheikh Zayed Road", lat:25.2256, lng:55.2688, phone:"+971-4-444-7444", tags:["5 כוכבים","קונרד","עיצוב"], featured:false },
    { id:35, name:"Grand Hyatt Dubai", nameEn:"Grand Hyatt Dubai", category:"hotels", subcategory:"5star", stars:5, description:"מתחם נופש ענק עם גינות טרופיות ב-37 דונם בלב דובאי.", image:"images/hotels/35.jpg", rating:4.4, price:"$$$", priceRange:"₪750-3,500 ללילה", address:"Oud Metha", lat:25.2200, lng:55.3100, phone:"+971-4-317-1234", tags:["5 כוכבים","היאט","גינות"], featured:false },
    { id:36, name:"Kempinski Mall of Emirates", nameEn:"Kempinski Hotel Mall of the Emirates", category:"hotels", subcategory:"5star", stars:5, description:"מחובר ישירות לקניון האמירויות, עם נוף לשלג של Ski Dubai.", image:"https://images.pexels.com/photos/14750359/pexels-photo-14750359.jpeg", rating:4.5, price:"$$$", priceRange:"₪900-4,000 ללילה", address:"Mall of Emirates", lat:25.1181, lng:55.2005, phone:"+971-4-341-0000", tags:["5 כוכבים","קניון","סקי"], featured:false },
    { id:37, name:"JW Marriott Marquis", nameEn:"JW Marriott Marquis Dubai", category:"hotels", subcategory:"5star", stars:5, description:"המלון הגבוה בעולם עם 72 קומות ו-14 מסעדות.", image:"images/hotels/37.jpg", rating:4.6, price:"$$$", priceRange:"₪700-3,000 ללילה", address:"Business Bay", lat:25.1867, lng:55.2625, phone:"+971-4-414-3000", tags:["5 כוכבים","הגבוה","Business Bay"], featured:true },
    { id:38, name:"Habtoor Grand Resort", nameEn:"Habtoor Grand Resort Autograph", category:"hotels", subcategory:"5star", stars:5, description:"נופש ענק על חוף JBR עם חוף פרטי ומסעדות רבות.", image:"https://images.pexels.com/photos/34972118/pexels-photo-34972118.jpeg", rating:4.3, price:"$$$", priceRange:"₪800-3,800 ללילה", address:"JBR", lat:25.0780, lng:55.1340, phone:"+971-4-399-5000", tags:["5 כוכבים","חוף","JBR"], featured:false },
    { id:39, name:"Le Meridien Airport", nameEn:"Le Meridien Dubai Hotel", category:"hotels", subcategory:"5star", stars:5, description:"קרוב לנמל התעופה עם בריכה ענקית ומרכז כנסים.", image:"https://images.pexels.com/photos/14750466/pexels-photo-14750466.jpeg", rating:4.2, price:"$$", priceRange:"₪600-2,500 ללילה", address:"Airport Road", lat:25.2500, lng:55.3400, phone:"+971-4-702-2455", tags:["5 כוכבים","שדה תעופה","כנסים"], featured:false },
    { id:40, name:"Hyatt Regency Deira", nameEn:"Hyatt Regency Dubai", category:"hotels", subcategory:"5star", stars:5, description:"היאט רג'נסי בדיירה עם גישה לשוק הזהב ונוף לקריק.", image:"https://images.pexels.com/photos/14750191/pexels-photo-14750191.jpeg", rating:4.2, price:"$$", priceRange:"₪600-2,500 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-209-6914", tags:["5 כוכבים","דיירה","קריק"], featured:false },

    // === 3-4 STARS ===
    { id:41, name:"Rove Downtown", nameEn:"Rove Downtown Dubai", category:"hotels", subcategory:"3-4star", stars:4, description:"מלון בוטיק צמוד לדובאי מול ולברג' חליפה, ערך מצוין למיקום.", image:"https://images.pexels.com/photos/10906732/pexels-photo-10906732.jpeg", rating:4.3, price:"$$", priceRange:"₪280-550 ללילה", address:"Downtown Dubai", lat:25.1972, lng:55.2744, phone:"+971-4-561-9999", tags:["3-4 כוכבים","מרכזי","ערך"], featured:true },
    { id:42, name:"Rove City Walk", nameEn:"Rove City Walk", category:"hotels", subcategory:"3-4star", stars:4, description:"מלון עיצובי ורענן באזור City Walk הטרנדי.", image:"https://images.pexels.com/photos/35394616/pexels-photo-35394616.jpeg", rating:4.2, price:"$$", priceRange:"₪260-500 ללילה", address:"City Walk", lat:25.2100, lng:55.2600, phone:"+971-4-561-9888", tags:["3-4 כוכבים","City Walk","עיצובי"], featured:false },
    { id:43, name:"Rove Trade Centre", nameEn:"Rove Trade Centre", category:"hotels", subcategory:"3-4star", stars:3, description:"בין דובאי העתיקה לחדשה, אידאלי לעסקים ותיירות.", image:"https://images.pexels.com/photos/29196946/pexels-photo-29196946.jpeg", rating:4.1, price:"$$", priceRange:"₪230-450 ללילה", address:"Trade Centre", lat:25.2256, lng:55.2688, phone:"+971-4-561-9777", tags:["3-4 כוכבים","מרכזי","עסקים"], featured:false },
    { id:44, name:"Citymax Al Barsha", nameEn:"Citymax Hotel Al Barsha", category:"hotels", subcategory:"3-4star", stars:3, description:"מלון תקציבי נוח בסמוך לקניון האמירויות עם בריכה על הגג.", image:"https://images.pexels.com/photos/34698507/pexels-photo-34698507.jpeg", rating:4.0, price:"$$", priceRange:"₪200-380 ללילה", address:"Al Barsha", lat:25.1181, lng:55.2005, phone:"+971-4-379-1999", tags:["3-4 כוכבים","תקציבי","קניון"], featured:false },
    { id:45, name:"Citymax Bur Dubai", nameEn:"Citymax Hotel Bur Dubai", category:"hotels", subcategory:"3-4star", stars:3, description:"סיטימקס בדובאי ההיסטורית עם בריכת גג, ליד מטרו.", image:"https://images.pexels.com/photos/36794534/pexels-photo-36794534.jpeg", rating:3.9, price:"$", priceRange:"₪180-350 ללילה", address:"Bur Dubai", lat:25.2500, lng:55.2900, phone:"+971-4-397-4000", tags:["3-4 כוכבים","היסטורי","מטרו"], featured:false },
    { id:46, name:"Premier Inn Airport", nameEn:"Premier Inn Dubai Airport", category:"hotels", subcategory:"3-4star", stars:3, description:"מלון אמין ונוח בסמוך לשדה התעופה לטיסות מוקדמות.", image:"https://images.pexels.com/photos/14750357/pexels-photo-14750357.jpeg", rating:4.0, price:"$$", priceRange:"₪200-380 ללילה", address:"Al Garhoud", lat:25.2500, lng:55.3400, phone:"+971-4-885-7888", tags:["3-4 כוכבים","שדה תעופה","נוח"], featured:false },
    { id:47, name:"ibis Al Barsha", nameEn:"ibis Dubai Al Barsha", category:"hotels", subcategory:"3-4star", stars:3, description:"איביס נקי ואמין בלב אל-ברשה, חדרים נוחים במחיר שפוי.", image:"https://images.pexels.com/photos/14749932/pexels-photo-14749932.jpeg", rating:3.8, price:"$", priceRange:"₪150-280 ללילה", address:"Al Barsha", lat:25.1181, lng:55.2005, phone:"+971-4-307-5000", tags:["3-4 כוכבים","איביס","זול"], featured:false },
    { id:48, name:"ibis Deira City Centre", nameEn:"ibis Dubai Deira City Centre", category:"hotels", subcategory:"3-4star", stars:3, description:"איביס קרוב לדיירה סיטי סנטר ותחנת מטרו.", image:"https://images.pexels.com/photos/14915303/pexels-photo-14915303.jpeg", rating:3.7, price:"$", priceRange:"₪140-260 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-295-7100", tags:["3-4 כוכבים","דיירה","מטרו"], featured:false },
    { id:49, name:"Ramada Downtown", nameEn:"Ramada by Wyndham Downtown Dubai", category:"hotels", subcategory:"3-4star", stars:4, description:"רמדה 4 כוכבים ב-Downtown עם נוף לאופק דובאי.", image:"images/hotels/hotel_1.jpeg", rating:4.1, price:"$$", priceRange:"₪350-650 ללילה", address:"Downtown Dubai", lat:25.1972, lng:55.2744, phone:"+971-4-506-0000", tags:["3-4 כוכבים","Downtown","נוף"], featured:false },
    { id:50, name:"Hilton Garden Inn Al Mina", nameEn:"Hilton Garden Inn Dubai Al Mina", category:"hotels", subcategory:"3-4star", stars:4, description:"הילטון גארדן אין עם ספא ובריכה מקורה ליד נמל דובאי.", image:"images/hotels/hotel_2.jpeg", rating:4.2, price:"$$", priceRange:"₪280-520 ללילה", address:"Al Mina, Bur Dubai", lat:25.2550, lng:55.2800, phone:"+971-4-407-1111", tags:["3-4 כוכבים","הילטון","ספא"], featured:false },
    { id:51, name:"Golden Tulip Deira", nameEn:"Golden Tulip Deira Hotel", category:"hotels", subcategory:"3-4star", stars:3, description:"גולדן טוליפ בדיירה עם בריכת גג, מרחק הליכה משוק הזהב.", image:"images/hotels/hotel_3.jpeg", rating:3.8, price:"$", priceRange:"₪180-340 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-267-7700", tags:["3-4 כוכבים","דיירה","שוק הזהב"], featured:false },
    { id:52, name:"Flora Grand Hotel", nameEn:"Flora Grand Hotel", category:"hotels", subcategory:"3-4star", stars:4, description:"4 כוכבים תקציבי פופולרי בדיירה, ידוע בנקיון.", image:"images/hotels/hotel_4.jpeg", rating:4.0, price:"$", priceRange:"₪170-320 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-236-9999", tags:["3-4 כוכבים","נקי","דיירה"], featured:false },
    { id:53, name:"Savoy Park Apartments", nameEn:"Savoy Park Hotel Apartments", category:"hotels", subcategory:"3-4star", stars:3, description:"דירות-מלון עם מטבחון, אידאלי לשהיות ארוכות ומשפחות.", image:"images/hotels/hotel_5.jpeg", rating:3.9, price:"$$", priceRange:"₪200-380 ללילה", address:"Bur Dubai", lat:25.2500, lng:55.2900, phone:"+971-4-359-0000", tags:["3-4 כוכבים","דירות","משפחות"], featured:false },
    { id:54, name:"Arabian Park Hotel", nameEn:"Arabian Park Hotel", category:"hotels", subcategory:"3-4star", stars:3, description:"מלון בסגנון ערבי עדין, שקט ונוח ליד שדה התעופה.", image:"images/hotels/hotel_6.jpeg", rating:3.8, price:"$", priceRange:"₪200-370 ללילה", address:"Al Garhoud", lat:25.2500, lng:55.3400, phone:"+971-4-295-5666", tags:["3-4 כוכבים","ערבי","שדה תעופה"], featured:false },
    { id:55, name:"Capitol Hotel Dubai", nameEn:"Capitol Hotel Dubai", category:"hotels", subcategory:"3-4star", stars:3, description:"תקציבי ותיק במרכז דובאי ליד תחנת מטרו.", image:"images/hotels/hotel_7.jpeg", rating:3.7, price:"$", priceRange:"₪220-400 ללילה", address:"Trade Centre", lat:25.2256, lng:55.2688, phone:"+971-4-345-0000", tags:["3-4 כוכבים","מרכזי","מטרו"], featured:false },
    { id:56, name:"Royal Ascot Hotel", nameEn:"Royal Ascot Hotel", category:"hotels", subcategory:"3-4star", stars:3, description:"סביר ומוערך בבר דובאי, יחס מצוין לכסף.", image:"images/hotels/hotel_8.jpeg", rating:3.8, price:"$", priceRange:"₪190-350 ללילה", address:"Bur Dubai", lat:25.2600, lng:55.2950, phone:"+971-4-352-0900", tags:["3-4 כוכבים","ערך","Bur Dubai"], featured:false },
    { id:57, name:"ibis One Central", nameEn:"ibis One Central Dubai", category:"hotels", subcategory:"3-4star", stars:3, description:"איביס מודרני בשכנות למרכז הסחר העולמי ו-DIFC.", image:"images/hotels/hotel_9.jpeg", rating:3.9, price:"$", priceRange:"₪160-300 ללילה", address:"One Central", lat:25.2256, lng:55.2688, phone:"+971-4-506-1000", tags:["3-4 כוכבים","DIFC","מודרני"], featured:false },
    { id:58, name:"Rove Healthcare City", nameEn:"Rove Healthcare City", category:"hotels", subcategory:"3-4star", stars:3, description:"רוב מינימליסטי ונוח לחובבי מרכז העיר.", image:"images/hotels/hotel_10.jpeg", rating:4.0, price:"$", priceRange:"₪200-400 ללילה", address:"Healthcare City", lat:25.2300, lng:55.3200, phone:"+971-4-561-9666", tags:["3-4 כוכבים","רוב","מינימלי"], featured:false },
    { id:59, name:"Smana Hotel Al Raffa", nameEn:"Smana Hotel Al Raffa", category:"hotels", subcategory:"3-4star", stars:3, description:"מעוצב ומודרני בשכונת אל-רפא ההיסטורית.", image:"images/hotels/hotel_11.jpeg", rating:3.8, price:"$", priceRange:"₪160-300 ללילה", address:"Al Raffa, Bur Dubai", lat:25.2550, lng:55.2850, phone:"+971-4-359-5000", tags:["3-4 כוכבים","מעוצב","היסטורי"], featured:false },
    { id:60, name:"Premier Inn Silicon Oasis", nameEn:"Premier Inn Dubai Silicon Oasis", category:"hotels", subcategory:"3-4star", stars:3, description:"פרמייר אין עם בריכה ושאטל חינם.", image:"images/hotels/hotel_12.jpeg", rating:4.1, price:"$$", priceRange:"₪230-420 ללילה", address:"Silicon Oasis", lat:25.1200, lng:55.3800, phone:"+971-4-501-6000", tags:["3-4 כוכבים","שאטל","בריכה"], featured:false },

    // === BUDGET ===
    { id:61, name:"XVA Art Hotel", nameEn:"XVA Art Hotel", category:"hotels", subcategory:"budget", stars:2, description:"מלון בוטיק אמנותי בשכונה ההיסטורית של אל-פהידי, ייחודי.", image:"images/hotels/hotel_13.jpeg", rating:4.3, price:"$$", priceRange:"₪250-450 ללילה", address:"Al Fahidi, Bur Dubai", lat:25.2633, lng:55.2975, phone:"+971-4-353-5383", tags:["תקציבי","אמנות","היסטורי"], featured:true },
    { id:62, name:"Orient Guest House", nameEn:"Orient Guest House", category:"hotels", subcategory:"budget", stars:2, description:"בית אורחים מסורתי עם חצרות פתוחות מול מוזיאון דובאי.", image:"images/hotels/hotel_14.jpeg", rating:4.1, price:"$", priceRange:"₪180-320 ללילה", address:"Al Fahidi, Bur Dubai", lat:25.2633, lng:55.2975, phone:"+971-4-351-9111", tags:["תקציבי","מסורתי","מוזיאון"], featured:false },
    { id:63, name:"Sheroes Hostel", nameEn:"Sheroes Hostel Business Bay", category:"hotels", subcategory:"budget", stars:1, description:"הוסטל מודרני עם תאי שינה וWiFi מהיר, אידאלי לתקציב נמוך.", image:"images/hotels/hotel_15.jpeg", rating:4.0, price:"$", priceRange:"₪80-180 ללילה", address:"Business Bay", lat:25.1867, lng:55.2625, phone:"+971-4-555-0001", tags:["תקציבי","הוסטל","צעירים"], featured:false },
    { id:64, name:"Somewhere Barsha Heights", nameEn:"Somewhere Hotel Barsha Heights", category:"hotels", subcategory:"budget", stars:3, description:"תקציבי עם בר, גג-ברים ובריכה, ערך מצוין.", image:"images/hotels/hotel_16.jpeg", rating:4.0, price:"$", priceRange:"₪150-280 ללילה", address:"Barsha Heights", lat:25.1000, lng:55.1700, phone:"+971-4-399-3399", tags:["תקציבי","בריכה","גג"], featured:false },
    { id:65, name:"ibis Styles Jumeirah", nameEn:"ibis Styles Dubai Jumeirah", category:"hotels", subcategory:"budget", stars:3, description:"איביס סטיילס צבעוני קרוב לחוף ג'ומיירה.", image:"images/hotels/hotel_17.jpeg", rating:3.9, price:"$", priceRange:"₪160-300 ללילה", address:"Jumeirah", lat:25.2100, lng:55.2500, phone:"+971-4-355-0000", tags:["תקציבי","צבעוני","חוף"], featured:false },
    { id:66, name:"Al Seef Heritage Hotel", nameEn:"Al Seef Heritage Hotel", category:"hotels", subcategory:"budget", stars:3, description:"מלון מורשת בעיצוב ערבי קלאסי על גדות קריק.", image:"images/hotels/hotel_18.jpeg", rating:4.2, price:"$$", priceRange:"₪300-500 ללילה", address:"Al Seef, Dubai Creek", lat:25.2633, lng:55.2975, phone:"+971-4-707-7077", tags:["תקציבי","מורשת","קריק"], featured:true },
    { id:67, name:"Tulip Inn Deira", nameEn:"Tulip Inn Dubai", category:"hotels", subcategory:"budget", stars:2, description:"פשוט ונקי בדיירה, קרוב לשוק הזהב ומטרו.", image:"images/hotels/hotel_19.jpeg", rating:3.5, price:"$", priceRange:"₪130-240 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-229-8000", tags:["תקציבי","דיירה","זול"], featured:false },
    { id:68, name:"Byblos Hotel", nameEn:"Byblos Hotel Dubai", category:"hotels", subcategory:"budget", stars:3, description:"מלון לבנוני עם מסעדה מזרח-תיכונית מצוינת.", image:"images/hotels/hotel_20.jpeg", rating:3.8, price:"$", priceRange:"₪200-380 ללילה", address:"Al Barsha, TECOM", lat:25.1000, lng:55.1700, phone:"+971-4-449-9900", tags:["תקציבי","לבנוני","TECOM"], featured:false },
    { id:69, name:"Sun & Sands Hotel", nameEn:"Sun & Sands Hotel", category:"hotels", subcategory:"budget", stars:2, description:"שמש וחול בדיירה, חדרים פשוטים ליד הנמל.", image:"images/hotels/hotel_21.jpeg", rating:3.4, price:"$", priceRange:"₪110-220 ללילה", address:"Deira, Baniyas", lat:25.2700, lng:55.2900, phone:"+971-4-223-2000", tags:["תקציבי","פשוט","דיירה"], featured:false },
    { id:70, name:"Dubai Youth Hostel", nameEn:"Dubai Youth Hostel", category:"hotels", subcategory:"budget", stars:1, description:"אכסניית הנוער הרשמית של דובאי, עם מעונות ממוזגים.", image:"images/hotels/hotel_22.jpeg", rating:3.6, price:"$", priceRange:"₪60-150 ללילה", address:"Al Qusais", lat:25.2800, lng:55.3800, phone:"+971-4-298-8151", tags:["תקציבי","אכסנייה","צעירים"], featured:false },
    { id:71, name:"Four Points Bur Dubai", nameEn:"Four Points by Sheraton Bur Dubai", category:"hotels", subcategory:"budget", stars:3, description:"Four Points נוח ואמין בבר דובאי עם בריכה.", image:"images/hotels/hotel_23.jpeg", rating:4.0, price:"$$", priceRange:"₪250-450 ללילה", address:"Bur Dubai", lat:25.2600, lng:55.2950, phone:"+971-4-397-7444", tags:["תקציבי","שרתון","בריכה"], featured:false },
    { id:72, name:"President Hotel", nameEn:"President Hotel Dubai", category:"hotels", subcategory:"budget", stars:2, description:"ותיק ואמין בבר דובאי, פופולרי בקרב מטיילים חוזרים.", image:"images/hotels/hotel_24.jpeg", rating:3.6, price:"$", priceRange:"₪150-270 ללילה", address:"Bur Dubai", lat:25.2600, lng:55.2950, phone:"+971-4-334-0000", tags:["תקציבי","ותיק","Bur Dubai"], featured:false },
    { id:73, name:"Hyatt Place Al Rigga", nameEn:"Hyatt Place Dubai Al Rigga", category:"hotels", subcategory:"budget", stars:3, description:"Hyatt Place תקציבי-פרמיום בדיירה עם ארוחת בוקר כלולה.", image:"https://images.pexels.com/photos/31820069/pexels-photo-31820069.jpeg", rating:4.1, price:"$$", priceRange:"₪220-400 ללילה", address:"Al Rigga, Deira", lat:25.2700, lng:55.2900, phone:"+971-4-233-1234", tags:["תקציבי","היאט","בוקר כלול"], featured:false },
    { id:74, name:"Al Ain Palace Hotel", nameEn:"Al Ain Palace Hotel Dubai", category:"hotels", subcategory:"budget", stars:2, description:"ותיק בבר דובאי עם אווירה ערבית, קרוב לבורג'ומן.", image:"https://images.pexels.com/photos/30245006/pexels-photo-30245006.jpeg", rating:3.5, price:"$", priceRange:"₪130-250 ללילה", address:"Bur Dubai", lat:25.2600, lng:55.2950, phone:"+971-4-426-0999", tags:["תקציבי","ערבי","ותיק"], featured:false },
    { id:75, name:"Concorde Deira", nameEn:"Concorde Deira Hotel", category:"hotels", subcategory:"budget", stars:3, description:"שופץ לאחרונה עם בריכת גג, ליד השוקים.", image:"https://images.pexels.com/photos/34596088/pexels-photo-34596088.jpeg", rating:3.7, price:"$", priceRange:"₪130-250 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-227-3000", tags:["תקציבי","משופץ","שוקים"], featured:false },
    { id:76, name:"Millennium Barsha Heights", nameEn:"Millennium Place Barsha Heights", category:"hotels", subcategory:"budget", stars:3, description:"מודרני בברשה הייטס, ידוע בשירות ביחס למחיר.", image:"https://images.pexels.com/photos/14749935/pexels-photo-14749935.jpeg", rating:4.0, price:"$$", priceRange:"₪220-400 ללילה", address:"Barsha Heights", lat:25.1000, lng:55.1700, phone:"+971-4-454-5555", tags:["תקציבי","מילניום","שירות"], featured:false },
    { id:77, name:"Citymax Business Bay", nameEn:"Citymax Hotel Business Bay", category:"hotels", subcategory:"budget", stars:3, description:"סיטימקס טרנדי ב-Business Bay עם בריכה ועיצוב עכשווי.", image:"https://images.pexels.com/photos/14749879/pexels-photo-14749879.jpeg", rating:3.9, price:"$$", priceRange:"₪200-380 ללילה", address:"Business Bay", lat:25.1867, lng:55.2625, phone:"+971-4-379-2000", tags:["תקציבי","Business Bay","בריכה"], featured:false },
    { id:78, name:"Aloft Dubai South", nameEn:"Aloft Dubai South", category:"hotels", subcategory:"budget", stars:3, description:"צעיר ומוזיקלי בדובאי סאות', קרוב לאקספו סיטי.", image:"https://images.pexels.com/photos/31851252/pexels-photo-31851252.jpeg", rating:3.8, price:"$$", priceRange:"₪200-380 ללילה", address:"Dubai South", lat:25.0000, lng:55.1800, phone:"+971-4-248-0000", tags:["תקציבי","Aloft","אקספו"], featured:false },
    { id:79, name:"Signature Al Barsha", nameEn:"Signature Hotel Al Barsha", category:"hotels", subcategory:"budget", stars:3, description:"בוטיק קטן בסגנון עכשווי, ערך טוב לכסף.", image:"https://images.pexels.com/photos/14750186/pexels-photo-14750186.jpeg", rating:3.8, price:"$", priceRange:"₪190-340 ללילה", address:"Al Barsha", lat:25.1181, lng:55.2005, phone:"+971-4-399-5599", tags:["תקציבי","בוטיק","Al Barsha"], featured:false },
    { id:80, name:"Comfort Inn Deira", nameEn:"Comfort Inn Dubai", category:"hotels", subcategory:"budget", stars:2, description:"שירות בסיסי תקין, אפשרות חסכונית לטיולים.", image:"https://images.pexels.com/photos/26838210/pexels-photo-26838210.jpeg", rating:3.4, price:"$", priceRange:"₪120-230 ללילה", address:"Deira", lat:25.2700, lng:55.2900, phone:"+971-4-205-0000", tags:["תקציבי","בסיסי","זול"], featured:false },
  ],
  restaurants: [
    // === ULTRA-LUXURY (12) ===
    { id:101, name:"Nobu Dubai", nameEn:"Nobu Dubai", category:"restaurants", subcategory:"ultra-luxury", description:"סניף מהמפורסמים בעולם של שף נובו — פיוז'ן יפני-פרואני.", image:"images/restaurants/101.jpg", rating:4.7, price:"$$$$", priceRange:"₪1,400-2,200 לזוג", address:"Atlantis The Palm", lat:25.1305, lng:55.1175, tags:["יוקרתי מאוד","יפני","סושי"], featured:true },
    { id:102, name:"Ossiano", nameEn:"Ossiano", category:"restaurants", subcategory:"ultra-luxury", description:"מסעדת פירות ים מעוטרת פרסים עם אקוריום מרהיב.", image:"images/restaurants/102.jpg", rating:4.9, price:"$$$$$", priceRange:"₪2,000-2,800 לזוג", address:"Atlantis The Palm", lat:25.1301, lng:55.1170, tags:["יוקרתי מאוד","מישלן","אקוריום"], featured:true },
    { id:103, name:"Zuma Dubai", nameEn:"Zuma Dubai", category:"restaurants", subcategory:"ultra-luxury", description:"יפני ראצ'י-בר אייקוני עם מוניטין עולמי ואווירה שוקקת.", image:"images/restaurants/rest_3.jpeg", rating:4.7, price:"$$$$", priceRange:"₪1,400-2,000 לזוג", address:"DIFC, Gate Village", lat:25.2126, lng:55.2800, tags:["יוקרתי מאוד","יפני","ברנץ'"], featured:true },
    { id:104, name:"Tresind Studio", nameEn:"Tresind Studio", category:"restaurants", subcategory:"ultra-luxury", description:"מסעדה הודית אוונגרדית בעלת כוכב מישלן, 20 קורסים.", image:"images/restaurants/rest_4.jpeg", rating:4.9, price:"$$$$$", priceRange:"₪1,600-2,400 לזוג", address:"Palm Jumeirah", lat:25.1118, lng:55.1394, tags:["יוקרתי מאוד","מישלן","הודי"], featured:false },
    { id:105, name:"11 Woodfire", nameEn:"11 Woodfire", category:"restaurants", subcategory:"ultra-luxury", description:"שף דני עם כוכב מישלן, בישול על אש עצים עם מרכיבים עונתיים.", image:"images/restaurants/rest_5.jpeg", rating:4.8, price:"$$$$", priceRange:"₪1,200-1,800 לזוג", address:"Alserkal Avenue, Al Quoz", lat:25.1488, lng:55.2246, tags:["יוקרתי מאוד","מישלן","אש"], featured:false },
    { id:106, name:"Stay by Yannick Alléno", nameEn:"Stay by Yannick Alleno", category:"restaurants", subcategory:"ultra-luxury", description:"שף צרפתי עם 3 כוכבי מישלן, קולינריה צרפתית עכשווית.", image:"images/restaurants/rest_6.jpeg", rating:4.8, price:"$$$$$", priceRange:"₪2,000-3,000 לזוג", address:"One&Only The Palm", lat:25.1102, lng:55.1368, tags:["יוקרתי מאוד","צרפתי","מישלן"], featured:false },
    { id:107, name:"COYA Dubai", nameEn:"COYA Dubai", category:"restaurants", subcategory:"ultra-luxury", description:"מסעדת פרואנית יוקרתית עם סביצ'ה וקוקטיילים.", image:"images/restaurants/rest_7.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,200-1,800 לזוג", address:"DIFC", lat:25.2118, lng:55.2801, tags:["יוקרתי מאוד","פרואני","קוקטיילים"], featured:false },
    { id:108, name:"Nusr-Et (Salt Bae)", nameEn:"Nusr-Et Steakhouse", category:"restaurants", subcategory:"ultra-luxury", description:"מסעדת הבשר המפורסמת של סולט ביי.", image:"images/restaurants/rest_8.jpeg", rating:4.3, price:"$$$$$", priceRange:"₪2,000-4,000 לזוג", address:"Jumeirah 1", lat:25.2176, lng:55.2591, tags:["יוקרתי מאוד","סטייק","מפורסם"], featured:true },
    { id:109, name:"Hakkasan Dubai", nameEn:"Hakkasan Dubai", category:"restaurants", subcategory:"ultra-luxury", description:"סינית יוקרתית בסגנון קנטוני עכשווי, ידועה ברחבי העולם.", image:"images/restaurants/rest_9.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,400-2,000 לזוג", address:"Emirates Towers", lat:25.2175, lng:55.2836, tags:["יוקרתי מאוד","סיני","קנטוני"], featured:false },
    { id:110, name:"Akira Back", nameEn:"Akira Back Dubai", category:"restaurants", subcategory:"ultra-luxury", description:"קוריאנית-יפנית של שף בעל כוכב מישלן, פיוז'ן נועז.", image:"images/restaurants/rest_10.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,200-1,800 לזוג", address:"W Dubai The Palm", lat:25.1128, lng:55.1398, tags:["יוקרתי מאוד","קוריאני","פיוז'ן"], featured:false },
    { id:111, name:"Dinner by Heston", nameEn:"Dinner by Heston Blumenthal", category:"restaurants", subcategory:"ultra-luxury", description:"שף בריטי מהולל עם תפריט יצירתי בהשראת היסטוריה קולינרית.", image:"images/restaurants/rest_11.jpeg", rating:4.8, price:"$$$$", priceRange:"₪1,800-2,500 לזוג", address:"Atlantis The Royal", lat:25.1304, lng:55.1172, tags:["יוקרתי מאוד","בריטי","יצירתי"], featured:false },
    // === LUXURY (12) ===
    { id:112, name:"Pierchic", nameEn:"Pierchic", category:"restaurants", subcategory:"luxury", description:"פירות ים רומנטית על רציף מעל הים, נוף לברג' אל ערב.", image:"images/restaurants/rest_12.jpeg", rating:4.7, price:"$$$$", priceRange:"₪1,000-1,600 לזוג", address:"Madinat Jumeirah", lat:25.1401, lng:55.1845, tags:["יוקרתי","פירות ים","רומנטי"], featured:true },
    { id:113, name:"La Petite Maison", nameEn:"La Petite Maison", category:"restaurants", subcategory:"luxury", description:"ביסטרו ניסואי אלגנטי עם מנות קלות ודגים טריים.", image:"images/restaurants/rest_13.jpeg", rating:4.6, price:"$$$$", priceRange:"₪900-1,400 לזוג", address:"DIFC", lat:25.2121, lng:55.2797, tags:["יוקרתי","צרפתי","ביסטרו"], featured:false },
    { id:114, name:"Scalini Dubai", nameEn:"Scalini Dubai", category:"restaurants", subcategory:"luxury", description:"איטלקית קלאסית ואלגנטית עם פסטות וטרטופי מובחרים.", image:"images/restaurants/rest_14.jpeg", rating:4.6, price:"$$$", priceRange:"₪900-1,400 לזוג", address:"Four Seasons, Jumeirah", lat:25.2052, lng:55.2344, tags:["יוקרתי","איטלקי","פסטה"], featured:false },
    { id:115, name:"Amazonico", nameEn:"Amazonico Dubai", category:"restaurants", subcategory:"luxury", description:"בסגנון ג'ונגל גשמי דרום-אמריקאי עם קוקטיילים וסביצ'ה.", image:"images/restaurants/rest_15.jpeg", rating:4.5, price:"$$$", priceRange:"₪1,000-1,600 לזוג", address:"DIFC", lat:25.2115, lng:55.2803, tags:["יוקרתי","דרום אמריקאי","ג'ונגל"], featured:false },
    { id:116, name:"Thiptara", nameEn:"Thiptara", category:"restaurants", subcategory:"luxury", description:"תאילנדית מסורתית עם נוף ישיר לברג' חליפה ואגם הריקודים.", image:"images/restaurants/rest_16.jpeg", rating:4.7, price:"$$$", priceRange:"₪800-1,200 לזוג", address:"Palace Downtown", lat:25.1957, lng:55.2745, tags:["יוקרתי","תאילנדי","נוף"], featured:true },
    { id:117, name:"Torno Subito", nameEn:"Torno Subito", category:"restaurants", subcategory:"luxury", description:"איטלקית של שף מסימו בוטורה בסגנון חופי שנות ה-70.", image:"images/restaurants/rest_17.jpeg", rating:4.6, price:"$$$", priceRange:"₪900-1,400 לזוג", address:"W Dubai The Palm", lat:25.1132, lng:55.1402, tags:["יוקרתי","איטלקי","רטרו"], featured:false },
    { id:118, name:"CÉ LA VI", nameEn:"CE LA VI Dubai", category:"restaurants", subcategory:"luxury", description:"אסייתית-אירופאית עם נוף עוצר נשימה מקו הרקיע.", image:"images/restaurants/rest_18.jpeg", rating:4.5, price:"$$$", priceRange:"₪900-1,400 לזוג", address:"Address Sky View", lat:25.1970, lng:55.2720, tags:["יוקרתי","גג","נוף"], featured:false },
    { id:119, name:"Rang Mahal", nameEn:"Rang Mahal", category:"restaurants", subcategory:"luxury", description:"הודית מלכותית עם מטבח מוגולי ומנות שף איכותיות.", image:"images/restaurants/rest_19.jpeg", rating:4.5, price:"$$$", priceRange:"₪700-1,100 לזוג", address:"JW Marriott Marquis", lat:25.1862, lng:55.2768, tags:["יוקרתי","הודי","מלכותי"], featured:false },
    { id:120, name:"Cipriani Dubai", nameEn:"Cipriani Dubai", category:"restaurants", subcategory:"luxury", description:"איטלקית אגדית מוונציה, מוכרת בפסטה ורוזה ספריץ.", image:"images/restaurants/rest_20.jpeg", rating:4.5, price:"$$$", priceRange:"₪1,000-1,600 לזוג", address:"Dubai Mall", lat:25.2048, lng:55.2762, tags:["יוקרתי","איטלקי","וונציה"], featured:false },
    { id:121, name:"Netsu", nameEn:"Netsu", category:"restaurants", subcategory:"luxury", description:"יפנית עכשווית עם מנות אומקאסה ובר סאקה מעולה.", image:"images/restaurants/rest_21.jpeg", rating:4.6, price:"$$$", priceRange:"₪1,000-1,600 לזוג", address:"Mandarin Oriental", lat:25.2155, lng:55.2589, tags:["יוקרתי","יפני","סאקה"], featured:false },
    { id:122, name:"Weslodge Saloon", nameEn:"Weslodge Saloon", category:"restaurants", subcategory:"luxury", description:"סטייקהאוס קנדי-אמריקאי אופנתי עם בר ויסקי.", image:"images/restaurants/rest_22.jpeg", rating:4.4, price:"$$$", priceRange:"₪800-1,200 לזוג", address:"JW Marriott Marquis", lat:25.1857, lng:55.2764, tags:["יוקרתי","סטייק","ויסקי"], featured:false },
    // === ISRAELI (12) ===
    { id:123, name:"HaSalon Dubai", nameEn:"HaSalon Dubai", category:"restaurants", subcategory:"israeli", description:"סניף דובאי של המסעדה האגדית של אייל שני — חוויית לילה מיוחדת.", image:"images/restaurants/rest_1.jpeg", rating:4.6, price:"$$$$", priceRange:"₪1,000-1,800 לזוג", address:"DIFC", lat:25.2122, lng:55.2799, tags:["ישראלי","אייל שני","חוויה"], featured:true },
    { id:124, name:"Armani/Kaf", nameEn:"Armani Kaf", category:"restaurants", subcategory:"israeli", description:"מסעדה כשרה יוקרתית בתוך מלון ארמני, תפריט בינלאומי.", image:"images/restaurants/rest_2.jpeg", rating:4.4, price:"$$$", priceRange:"₪800-1,400 לזוג", address:"Armani Hotel, Burj Khalifa", lat:25.1972, lng:55.2744, tags:["ישראלי","כשר","יוקרה"], featured:true },
    { id:125, name:"Noa Dubai", nameEn:"Noa Dubai", category:"restaurants", subcategory:"israeli", description:"ישראלית עכשווית עם מנות ים-תיכוניות, חומוס ומנות שף.", image:"images/restaurants/rest_3.jpeg", rating:4.4, price:"$$", priceRange:"₪600-1,000 לזוג", address:"Bluewaters Island", lat:25.0798, lng:55.1224, tags:["ישראלי","ים תיכוני","עכשווי"], featured:false },
    { id:126, name:"Miznon Dubai", nameEn:"Miznon Dubai", category:"restaurants", subcategory:"israeli", description:"רשת הפיתות של אביב משה — פיתה, ירקות צלויים, בורגר.", image:"images/restaurants/rest_4.jpeg", rating:4.5, price:"$", priceRange:"₪200-350 לזוג", address:"City Walk", lat:25.2074, lng:55.2480, tags:["ישראלי","פיתה","אביב משה"], featured:true },
    { id:127, name:"Uri Buri Dubai", nameEn:"Uri Buri Dubai", category:"restaurants", subcategory:"israeli", description:"ענף של מסעדת הדגים המפורסמת מעכו, פירות ים ים-תיכוניים.", image:"images/restaurants/rest_5.jpeg", rating:4.5, price:"$$$", priceRange:"₪700-1,200 לזוג", address:"Palm Jumeirah", lat:25.1124, lng:55.1390, tags:["ישראלי","דגים","עכו"], featured:false },
    { id:128, name:"Sabich & More", nameEn:"Sabich and More", category:"restaurants", subcategory:"israeli", description:"סביח, פלאפל, סלטים ישראליים ומיצים טריים.", image:"images/restaurants/rest_6.jpeg", rating:4.3, price:"$", priceRange:"₪150-280 לזוג", address:"Al Wasl Road", lat:25.2115, lng:55.2510, tags:["ישראלי","סביח","פלאפל"], featured:false },
    { id:129, name:"Shalom", nameEn:"Shalom Restaurant", category:"restaurants", subcategory:"israeli", description:"מסעדה כשרה עם מנות מזרח-תיכוניות קלאסיות.", image:"images/restaurants/rest_7.jpeg", rating:4.2, price:"$$", priceRange:"₪350-600 לזוג", address:"Al Rigga, Deira", lat:25.2579, lng:55.3273, tags:["ישראלי","כשר","מזרחי"], featured:false },
    { id:130, name:"Kosher Dubai", nameEn:"Kosher Dubai", category:"restaurants", subcategory:"israeli", description:"מסעדה כשרה עם ארוחות כשרות לפסח, שבת ויום יום.", image:"images/restaurants/rest_8.jpeg", rating:4.1, price:"$$", priceRange:"₪500-800 לזוג", address:"Jumeirah", lat:25.2180, lng:55.2600, tags:["ישראלי","כשר","שבת"], featured:false },
    { id:131, name:"The Market Table", nameEn:"The Market Table", category:"restaurants", subcategory:"israeli", description:"גורמה כשרה עם תפריט עונתי ואירועים שבתיים.", image:"images/restaurants/rest_9.jpeg", rating:4.2, price:"$$", priceRange:"₪600-1,000 לזוג", address:"Downtown Dubai", lat:25.1985, lng:55.2760, tags:["ישראלי","כשר","עונתי"], featured:false },
    { id:132, name:"Basta Art Café", nameEn:"Basta Art Cafe", category:"restaurants", subcategory:"israeli", description:"קפה ים-תיכוני בוהמי, פופולרי מאוד בקרב הקהילה הישראלית.", image:"images/restaurants/rest_10.jpeg", rating:4.4, price:"$", priceRange:"₪200-400 לזוג", address:"Al Fahidi, Bastakiya", lat:25.2630, lng:55.3004, tags:["ישראלי","בוהמי","קפה"], featured:false },
    { id:133, name:"The Beefbar", nameEn:"The Beefbar", category:"restaurants", subcategory:"israeli", description:"בשר יוקרתי עם אפשרות תפריט כשר.", image:"images/restaurants/rest_11.jpeg", rating:4.5, price:"$$$", priceRange:"₪900-1,500 לזוג", address:"DIFC", lat:25.2119, lng:55.2798, tags:["ישראלי","בשר","יוקרה"], featured:false },
    { id:134, name:"Mei Wei", nameEn:"Mei Wei", category:"restaurants", subcategory:"israeli", description:"סינית כשרה עם דים סאם ומנות ווק.", image:"images/restaurants/rest_12.jpeg", rating:4.2, price:"$$", priceRange:"₪400-700 לזוג", address:"Dubai Marina", lat:25.0770, lng:55.1390, tags:["ישראלי","כשר","סיני"], featured:false },
    // === LEBANESE (12) ===
    { id:135, name:"Em Sherif", nameEn:"Em Sherif", category:"restaurants", subcategory:"lebanese", description:"לבנונית יוקרתית עם מנות ביתיות ועיצוב ארמון.", image:"images/restaurants/rest_13.jpeg", rating:4.7, price:"$$$", priceRange:"₪700-1,100 לזוג", address:"Business Bay", lat:25.1872, lng:55.2780, tags:["לבנוני","יוקרתי","ביתי"], featured:true },
    { id:136, name:"Al Nafoorah", nameEn:"Al Nafoorah", category:"restaurants", subcategory:"lebanese", description:"אחת הטובות בדובאי, מנות מסורתיות אלגנטיות.", image:"images/restaurants/rest_14.jpeg", rating:4.6, price:"$$", priceRange:"₪600-1,000 לזוג", address:"Emirates Towers", lat:25.2172, lng:55.2839, tags:["לבנוני","מסורתי","אלגנטי"], featured:true },
    { id:137, name:"Zaroob", nameEn:"Zaroob", category:"restaurants", subcategory:"lebanese", description:"רשת שאמית פופולרית עם פלאפל, שווארמה ופטייר.", image:"images/restaurants/rest_15.jpeg", rating:4.5, price:"$", priceRange:"₪150-280 לזוג", address:"Sheikh Zayed Road", lat:25.2010, lng:55.2715, tags:["לבנוני","שווארמה","זול"], featured:false },
    { id:138, name:"Leila", nameEn:"Leila", category:"restaurants", subcategory:"lebanese", description:"מודרנית עם עיצוב כפרי-אינטימי ותפריט ביתי אותנטי.", image:"images/restaurants/rest_16.jpeg", rating:4.6, price:"$$", priceRange:"₪400-700 לזוג", address:"City Walk", lat:25.2078, lng:55.2482, tags:["לבנוני","כפרי","רומנטי"], featured:false },
    { id:139, name:"Wafi Gourmet", nameEn:"Wafi Gourmet", category:"restaurants", subcategory:"lebanese", description:"חנות-מסעדה עם מוצרי גורמה, גבינות ומנות מבושלות.", image:"images/restaurants/rest_17.jpeg", rating:4.5, price:"$$", priceRange:"₪300-550 לזוג", address:"Wafi Mall", lat:25.2308, lng:55.3148, tags:["לבנוני","גורמה","גבינות"], featured:false },
    { id:140, name:"Byblos Sur Mer", nameEn:"Byblos Sur Mer", category:"restaurants", subcategory:"lebanese", description:"ים-תיכונית עם דגים ופירות ים על שפת הים.", image:"images/restaurants/rest_18.jpeg", rating:4.4, price:"$$", priceRange:"₪500-800 לזוג", address:"Festival City", lat:25.2214, lng:55.3505, tags:["לבנוני","דגים","ים"], featured:false },
    { id:141, name:"Almaz by Momo", nameEn:"Almaz by Momo", category:"restaurants", subcategory:"lebanese", description:"צפון-אפריקאית ולבנונית בהשראת מרקש, מוזיקה חיה.", image:"images/restaurants/rest_19.jpeg", rating:4.4, price:"$$", priceRange:"₪600-1,000 לזוג", address:"Mall of the Emirates", lat:25.1183, lng:55.2002, tags:["לבנוני","מרוקאי","מוזיקה"], featured:false },
    { id:142, name:"Operation Falafel", nameEn:"Operation Falafel", category:"restaurants", subcategory:"lebanese", description:"רשת פלאפל, חומוס ושווארמה ברמה גבוהה.", image:"images/restaurants/142.jpg", rating:4.2, price:"$", priceRange:"₪40-100 לזוג", address:"סניפים בכל דובאי", lat:25.2048, lng:55.2708, tags:["לבנוני","פלאפל","זול"], featured:false },
    { id:143, name:"Al Hallab", nameEn:"Al Hallab", category:"restaurants", subcategory:"lebanese", description:"רשת מפורסמת עם מנות מסורתיות וכנאפה מדהימה.", image:"images/restaurants/rest_21.jpeg", rating:4.4, price:"$$", priceRange:"₪300-550 לזוג", address:"Dubai Mall", lat:25.1985, lng:55.2796, tags:["לבנוני","כנאפה","מסורתי"], featured:false },
    { id:144, name:"Baalbek", nameEn:"Baalbek", category:"restaurants", subcategory:"lebanese", description:"קלאסית עם מנגל, מזה נדיב ואוכל ביתי אמיתי.", image:"images/restaurants/rest_22.jpeg", rating:4.3, price:"$", priceRange:"₪200-380 לזוג", address:"Karama", lat:25.2387, lng:55.3068, tags:["לבנוני","מנגל","ביתי"], featured:false },
    { id:145, name:"Mezza House", nameEn:"Mezza House", category:"restaurants", subcategory:"lebanese", description:"מבחר מזה עשיר, גריל ונרגילה.", image:"images/restaurants/rest_23.jpeg", rating:4.4, price:"$$", priceRange:"₪350-600 לזוג", address:"JBR Walk", lat:25.0790, lng:55.1340, tags:["לבנוני","מזה","נרגילה"], featured:false },
    { id:146, name:"Sababa", nameEn:"Sababa", category:"restaurants", subcategory:"lebanese", description:"לבנונית עם טאץ' מודרני, שאקשוקה ולבנה.", image:"images/restaurants/rest_1.jpeg", rating:4.3, price:"$", priceRange:"₪250-450 לזוג", address:"Jumeirah 1", lat:25.2185, lng:55.2598, tags:["לבנוני","מודרני","שאקשוקה"], featured:false },
    // === TURKISH (12) ===
    { id:147, name:"Günaydın", nameEn:"Gunaydin", category:"restaurants", subcategory:"turkish", description:"רשת הסטייק הטורקי המפורסמת — בשר פרמיום.", image:"images/restaurants/rest_2.jpeg", rating:4.6, price:"$$$", priceRange:"₪600-1,000 לזוג", address:"Dubai Mall", lat:25.1975, lng:55.2796, tags:["טורקי","סטייק","פרמיום"], featured:true },
    { id:148, name:"Ottoman's Life", nameEn:"Ottomans Life", category:"restaurants", subcategory:"turkish", description:"עות'מנית מרשימה עם עיצוב ארמון ותפריט בשר.", image:"images/restaurants/rest_3.jpeg", rating:4.5, price:"$$", priceRange:"₪600-1,000 לזוג", address:"Business Bay", lat:25.1858, lng:55.2762, tags:["טורקי","עות'מני","ארמון"], featured:false },
    { id:149, name:"Bosporus", nameEn:"Bosporus", category:"restaurants", subcategory:"turkish", description:"ותיקה ומוכרת עם מנות ביתיות כמו מוסאקה ועושמה.", image:"images/restaurants/rest_4.jpeg", rating:4.5, price:"$$", priceRange:"₪400-700 לזוג", address:"Jumeirah", lat:25.2190, lng:55.2610, tags:["טורקי","ביתי","מוסאקה"], featured:false },
    { id:150, name:"Divan", nameEn:"Divan", category:"restaurants", subcategory:"turkish", description:"בסגנון איסטנבול המודרני עם מנות ים תיכוניות.", image:"images/restaurants/rest_5.jpeg", rating:4.4, price:"$$$", priceRange:"₪700-1,100 לזוג", address:"DIFC", lat:25.2120, lng:55.2800, tags:["טורקי","מודרני","DIFC"], featured:false },
    { id:151, name:"Safir Istanbul", nameEn:"Safir Istanbul", category:"restaurants", subcategory:"turkish", description:"אותנטית עם קבב עשן, מנטי ותה טורקי.", image:"images/restaurants/rest_6.jpeg", rating:4.4, price:"$", priceRange:"₪300-550 לזוג", address:"Al Barsha", lat:25.1082, lng:55.1982, tags:["טורקי","קבב","אותנטי"], featured:false },
    { id:152, name:"Istanbul Flower", nameEn:"Istanbul Flower", category:"restaurants", subcategory:"turkish", description:"פופולרית עם אווירה חמה, קבב לולה ולוקמה.", image:"images/restaurants/rest_7.jpeg", rating:4.3, price:"$", priceRange:"₪200-380 לזוג", address:"Al Rigga, Deira", lat:25.2585, lng:55.3278, tags:["טורקי","לולה","זול"], featured:false },
    { id:153, name:"Topkapi", nameEn:"Topkapi", category:"restaurants", subcategory:"turkish", description:"מסורתית על שם ארמון טופקאפי, מנות סולת ודולמה.", image:"images/restaurants/rest_8.jpeg", rating:4.2, price:"$", priceRange:"₪300-500 לזוג", address:"Oud Metha", lat:25.2333, lng:55.3155, tags:["טורקי","מסורתי","דולמה"], featured:false },
    { id:154, name:"Kasr Al Bahar", nameEn:"Kasr Al Bahar", category:"restaurants", subcategory:"turkish", description:"אלגנטית עם מנות עות'מניות ונוף לדובאי קריק.", image:"images/restaurants/rest_9.jpeg", rating:4.4, price:"$$", priceRange:"₪500-800 לזוג", address:"Wafi Mall", lat:25.2311, lng:55.3152, tags:["טורקי","נוף","קריק"], featured:false },
    { id:155, name:"Anatolian", nameEn:"Anatolian", category:"restaurants", subcategory:"turkish", description:"גריל טורקי עם מנגל ושיש-קבב.", image:"images/restaurants/rest_10.jpeg", rating:4.3, price:"$", priceRange:"₪250-420 לזוג", address:"Karama", lat:25.2390, lng:55.3070, tags:["טורקי","מנגל","קבב"], featured:false },
    { id:156, name:"Hünkar", nameEn:"Hunkar", category:"restaurants", subcategory:"turkish", description:"קלאסית עם הונקאר בגדי ועישמה-טאש-קבב.", image:"images/restaurants/rest_11.jpeg", rating:4.3, price:"$$", priceRange:"₪350-600 לזוג", address:"JLT", lat:25.0690, lng:55.1432, tags:["טורקי","קלאסי","JLT"], featured:false },
    { id:157, name:"Nusr-Et Burger", nameEn:"Nusr-Et Burger", category:"restaurants", subcategory:"turkish", description:"הגרסה הזולה של סולט ביי — המבורגרים תורכיים.", image:"images/restaurants/rest_12.jpeg", rating:4.3, price:"$", priceRange:"₪300-550 לזוג", address:"JBR", lat:25.0788, lng:55.1338, tags:["טורקי","המבורגר","סולט ביי"], featured:false },
    { id:158, name:"Sofra bld", nameEn:"Sofra bld", category:"restaurants", subcategory:"turkish", description:"בופה טורקית עם מגוון מנות עות'מניות ומאפים.", image:"images/restaurants/rest_13.jpeg", rating:4.4, price:"$", priceRange:"₪200-350 לזוג", address:"Bur Dubai", lat:25.2480, lng:55.3210, tags:["טורקי","בופה","מאפים"], featured:false },
    // === LOCAL/POPULAR (12) ===
    { id:159, name:"Al Fanar", nameEn:"Al Fanar", category:"restaurants", subcategory:"local", description:"אמיראתית אותנטית עם עיצוב קלאסי ומנות כמו הריס ומצבוס.", image:"images/restaurants/159.jpg", rating:4.5, price:"$$", priceRange:"₪300-550 לזוג", address:"Festival City Mall", lat:25.2218, lng:55.3508, tags:["עממי","אמיראתי","מסורתי"], featured:true },
    { id:160, name:"Arabian Tea House", nameEn:"Arabian Tea House", category:"restaurants", subcategory:"local", description:"קפה אמיראתי איקוני בלב אל-פאהידי עם לאחם ולוקמה.", image:"images/restaurants/160.jpg", rating:4.6, price:"$", priceRange:"₪150-280 לזוג", address:"Al Fahidi, Bur Dubai", lat:25.2631, lng:55.3006, tags:["עממי","אמיראתי","היסטורי"], featured:true },
    { id:161, name:"Ravi Restaurant", nameEn:"Ravi Restaurant", category:"restaurants", subcategory:"local", description:"פקיסטנית-הודית אגדית מ-1978, אוכל מדהים במחירי רצפה.", image:"images/restaurants/rest_16.jpeg", rating:4.6, price:"$", priceRange:"₪80-160 לזוג", address:"Satwa", lat:25.2255, lng:55.2632, tags:["עממי","פקיסטני","אגדי"], featured:true },
    { id:162, name:"Bu Qtair", nameEn:"Bu Qtair", category:"restaurants", subcategory:"local", description:"על שפת הים עם דגים טריים מטוגנים וקארי מקומי.", image:"images/restaurants/rest_17.jpeg", rating:4.7, price:"$", priceRange:"₪120-220 לזוג", address:"Fishing Harbour, Jumeirah", lat:25.1865, lng:55.2385, tags:["עממי","דגים","חוף"], featured:false },
    { id:163, name:"Karachi Darbar", nameEn:"Karachi Darbar", category:"restaurants", subcategory:"local", description:"פקיסטנית עממית, ביריאני ונהרי — פופולרית גם בקרב ישראלים.", image:"images/restaurants/rest_18.jpeg", rating:4.5, price:"$", priceRange:"₪80-160 לזוג", address:"Bur Dubai & Deira", lat:25.2642, lng:55.3012, tags:["עממי","פקיסטני","ביריאני"], featured:false },
    { id:164, name:"Gazebo", nameEn:"Gazebo", category:"restaurants", subcategory:"local", description:"רשת הודית פופולרית עם קארי, תנדורי ונאן.", image:"images/restaurants/rest_19.jpeg", rating:4.4, price:"$", priceRange:"₪200-380 לזוג", address:"Sheikh Zayed Road", lat:25.1995, lng:55.2700, tags:["עממי","הודי","קארי"], featured:false },
    { id:165, name:"Asha's", nameEn:"Ashas", category:"restaurants", subcategory:"local", description:"הודית בסגנון בוליווד בהשראת הזמרת אשא בוסלה.", image:"images/restaurants/rest_20.jpeg", rating:4.4, price:"$$", priceRange:"₪300-550 לזוג", address:"Wafi Mall", lat:25.2314, lng:55.3155, tags:["עממי","הודי","בוליווד"], featured:false },
    { id:166, name:"Calicut Paragon", nameEn:"Calicut Paragon", category:"restaurants", subcategory:"local", description:"קרלה-הודית אותנטית עם דוסה, ביריאני ופירות ים.", image:"images/restaurants/rest_21.jpeg", rating:4.5, price:"$", priceRange:"₪120-220 לזוג", address:"Karama", lat:25.2380, lng:55.3065, tags:["עממי","הודי","דוסה"], featured:false },
    { id:167, name:"Bait Al Wakeel", nameEn:"Bait Al Wakeel", category:"restaurants", subcategory:"local", description:"אמיראתית עתיקה בבניין היסטורי על הקריק.", image:"images/restaurants/rest_22.jpeg", rating:4.3, price:"$", priceRange:"₪200-380 לזוג", address:"Dubai Creek, Bur Dubai", lat:25.2638, lng:55.3015, tags:["עממי","היסטורי","קריק"], featured:false },
    { id:168, name:"Special Ostadi", nameEn:"Special Ostadi", category:"restaurants", subcategory:"local", description:"גריל איראנית-הודית עממית עם קבב ושיניות.", image:"images/restaurants/rest_23.jpeg", rating:4.4, price:"$", priceRange:"₪150-280 לזוג", address:"Al Rigga, Deira", lat:25.2581, lng:55.3280, tags:["עממי","איראני","קבב"], featured:false },
    { id:169, name:"Lal Qila", nameEn:"Lal Qila", category:"restaurants", subcategory:"local", description:"הודית קלאסית מוגולית עם מנות סרמה ועוף בוטרי.", image:"images/restaurants/rest_1.jpeg", rating:4.3, price:"$", priceRange:"₪200-380 לזוג", address:"Bur Dubai", lat:25.2580, lng:55.3002, tags:["עממי","הודי","מוגולי"], featured:false },
    { id:170, name:"Al Shindagha", nameEn:"Al Shindagha", category:"restaurants", subcategory:"local", description:"אמיראתית מסורתית — סמבוסה, לוקמה ומחיבוס.", image:"images/restaurants/170.jpg", rating:4.3, price:"$", priceRange:"₪150-280 לזוג", address:"Bur Dubai", lat:25.2680, lng:55.3038, tags:["עממי","אמיראתי","סמבוסה"], featured:false },
    // === STREET FOOD (12) ===
    { id:171, name:"Al Ustad Kebab", nameEn:"Al Ustad Special Kebab", category:"restaurants", subcategory:"street", description:"קבב איראני קלאסי, פתוח מ-1978, מהוותיקות בדובאי.", image:"images/restaurants/rest_3.jpeg", rating:4.6, price:"$", priceRange:"₪80-150 לזוג", address:"Bur Dubai", lat:25.2595, lng:55.3005, tags:["אוכל רחוב","קבב","ותיק"], featured:true },
    { id:172, name:"Al Mallah", nameEn:"Al Mallah", category:"restaurants", subcategory:"street", description:"שווארמה ומנות רחוב ערביות ותיקה בסאטווה.", image:"images/restaurants/rest_4.jpeg", rating:4.7, price:"$", priceRange:"₪60-120 לזוג", address:"Satwa", lat:25.2248, lng:55.2620, tags:["אוכל רחוב","שווארמה","אגדי"], featured:true },
    { id:173, name:"Filli Café", nameEn:"Filli Cafe", category:"restaurants", subcategory:"street", description:"בית קפה אמיראתי איקוני, מפורסם בצ'אי הראה (תה עשן).", image:"images/restaurants/rest_5.jpeg", rating:4.7, price:"$", priceRange:"₪30-80 לזוג", address:"סניפים בכל דובאי", lat:25.2280, lng:55.3260, tags:["אוכל רחוב","תה","אמיראתי"], featured:false },
    { id:174, name:"Shawarma Al Sham", nameEn:"Shawarma Al Sham", category:"restaurants", subcategory:"street", description:"שווארמה ערבית ענקית עם טחינה, פופולרית מאוד.", image:"images/restaurants/rest_6.jpeg", rating:4.6, price:"$", priceRange:"₪20-50 לזוג", address:"Al Rigga, Deira", lat:25.2578, lng:55.3281, tags:["אוכל רחוב","שווארמה","זול מאוד"], featured:false },
    { id:175, name:"Samad Al Iraqi", nameEn:"Samad Al Iraqi", category:"restaurants", subcategory:"street", description:"עיראקית עם פטה, כבב ולחם טנור חם.", image:"images/restaurants/rest_7.jpeg", rating:4.5, price:"$", priceRange:"₪100-200 לזוג", address:"Deira", lat:25.2560, lng:55.3290, tags:["אוכל רחוב","עיראקי","טנור"], featured:false },
    { id:176, name:"Karak House", nameEn:"Karak House", category:"restaurants", subcategory:"street", description:"צ'אי קארק ומנות רחוב הודיות, הכי אותנטי.", image:"images/restaurants/rest_8.jpeg", rating:4.0, price:"$", priceRange:"₪10-40 לזוג", address:"סניפים בכל דובאי", lat:25.2048, lng:55.2708, tags:["אוכל רחוב","תה","הודי"], featured:false },
    { id:177, name:"Hatam", nameEn:"Hatam", category:"restaurants", subcategory:"street", description:"רחוב איראנית עם קבב, חוביז ואורז זעפרן.", image:"images/restaurants/rest_9.jpeg", rating:4.5, price:"$", priceRange:"₪100-180 לזוג", address:"Oud Metha", lat:25.2330, lng:55.3160, tags:["אוכל רחוב","איראני","זעפרן"], featured:false },
    { id:178, name:"Lulu's Shawarma", nameEn:"Lulus Shawarma", category:"restaurants", subcategory:"street", description:"שווארמה עוף וטלה עסיסית, תור בלתי נגמר.", image:"images/restaurants/rest_10.jpeg", rating:4.5, price:"$", priceRange:"₪25-60 לזוג", address:"JBR", lat:25.0795, lng:55.1342, tags:["אוכל רחוב","שווארמה","JBR"], featured:false },
    { id:179, name:"Times of Arabia", nameEn:"Times of Arabia", category:"restaurants", subcategory:"street", description:"ארוחת בוקר אמיראתית עם לוקמה, חלאוה וצ'אי.", image:"images/restaurants/rest_11.jpeg", rating:4.5, price:"$", priceRange:"₪50-100 לזוג", address:"Al Seef, Dubai Creek", lat:25.2615, lng:55.3020, tags:["אוכל רחוב","בוקר","אמיראתי"], featured:false },
    { id:180, name:"Pannahar", nameEn:"Pannahar", category:"restaurants", subcategory:"street", description:"בנגלדש-הודית עם ביריאני, דאל וקארי זולים.", image:"images/restaurants/rest_12.jpeg", rating:4.3, price:"$", priceRange:"₪60-110 לזוג", address:"Al Quoz", lat:25.1480, lng:55.2240, tags:["אוכל רחוב","בנגלדשי","זול"], featured:false },
    { id:181, name:"Food Village Karama", nameEn:"Food Village Karama", category:"restaurants", subcategory:"street", description:"שוק אוכל עממי עם דוכנים מאסיה — הודי, פיליפיני, מצרי.", image:"images/restaurants/rest_13.jpeg", rating:4.4, price:"$", priceRange:"₪50-100 לזוג", address:"Karama", lat:25.2388, lng:55.3060, tags:["אוכל רחוב","שוק","מגוון"], featured:false },
    { id:182, name:"Eat & Drink", nameEn:"Eat and Drink", category:"restaurants", subcategory:"street", description:"חומוס ופול מצרית-לבנונית, ארוחת בוקר פופולרית.", image:"images/restaurants/rest_14.jpeg", rating:4.4, price:"$", priceRange:"₪60-120 לזוג", address:"Karama", lat:25.2385, lng:55.3072, tags:["אוכל רחוב","חומוס","בוקר"], featured:false },
  ],
  attractions: [
    // === LANDMARKS ===
    { id:201, name:"ברג' חליפה", nameEn:"Burj Khalifa", category:"attractions", subcategory:"landmark", description:"המגדל הגבוה בעולם (828 מ'), תצפית פנורמית עוצרת נשימה מקומה 148.", image:"images/attractions/201.jpg", rating:4.9, price:"$$", priceRange:"₪149-369", address:"Downtown Dubai", lat:25.1972, lng:55.2744, phone:"+971-4-888-8888", tags:["ציון דרך","תצפית","חובה"], webcam:"https://www.webcamtaxi.com/en/united-arab-emirates/dubai/burj-khalifa-lake-dubai.html", featured:true },
    { id:202, name:"Dubai Mall", nameEn:"Dubai Mall", category:"attractions", subcategory:"landmark", description:"אחד מרכזי הקניות הגדולים בעולם עם חנויות, מסעדות ואטרקציות בלתי נגמרות.", image:"images/attractions/202.jpg", rating:4.7, price:"חינם", priceRange:"כניסה חינם", address:"Downtown Dubai", lat:25.1985, lng:55.2796, phone:"+971-4-362-7500", tags:["ציון דרך","קניות","משפחות"], webcam:"https://www.webcamtaxi.com/en/united-arab-emirates/dubai/burj-khalifa-lake-dubai.html", featured:true },
    { id:203, name:"פאלם ג'ומיירה", nameEn:"Palm Jumeirah", category:"attractions", subcategory:"landmark", description:"אי מלאכותי בצורת דקל, אחד מפלאי ההנדסה המודרניים של דובאי.", image:"images/attractions/203.jpg", rating:4.6, price:"$", priceRange:"₪25 מונורייל", address:"Palm Jumeirah", lat:25.1124, lng:55.1390, tags:["ציון דרך","אי","מונורייל"], webcam:"https://www.skylinewebcams.com/en/webcam/united-arab-emirates/dubai/dubai/dubai-marina.html", featured:true },
    { id:204, name:"Dubai Frame", nameEn:"Dubai Frame", category:"attractions", subcategory:"landmark", description:"מסגרת ענקית בצורת מלבן המציעה נוף ייחודי של דובאי הישנה והחדשה.", image:"images/attractions/204.jpg", rating:4.5, price:"$", priceRange:"₪50", address:"Zabeel Park", lat:25.2354, lng:55.3003, phone:"+971-4-354-6666", tags:["ציון דרך","תצפית","צילום"], featured:true },
    { id:205, name:"דובאי מרינה", nameEn:"Dubai Marina", category:"attractions", subcategory:"landmark", description:"שכונת נמל מודרנית עם גורדי שחקים, מסעדות ופרומנדה לאורך תעלת ים.", image:"images/attractions/205.jpg", rating:4.6, price:"חינם", priceRange:"חינם", address:"Dubai Marina", lat:25.0804, lng:55.1404, tags:["ציון דרך","פרומנדה","חינם"], featured:false },
    { id:206, name:"עין דובאי", nameEn:"Ain Dubai", category:"attractions", subcategory:"landmark", description:"הגלגל הענק הגבוה בעולם (250 מ') עם נוף פנורמי עוצר נשימה.", image:"images/attractions/206.jpg", rating:4.6, price:"$$", priceRange:"₪130-250", address:"Bluewaters Island", lat:25.0825, lng:55.1228, tags:["ציון דרך","תצפית","רומנטי"], featured:true },
    { id:207, name:"מדינת ג'ומיירה", nameEn:"Madinat Jumeirah", category:"attractions", subcategory:"landmark", description:"מלון ומרכז קניות מפואר בסגנון ערבי מסורתי עם תעלות ואווירה קסומה.", image:"images/attractions/207.jpg", rating:4.7, price:"חינם", priceRange:"כניסה חינם", address:"Jumeirah", lat:25.1348, lng:55.1863, tags:["ציון דרך","ערבי","תעלות"], featured:false },
    { id:208, name:"דובאי קריק", nameEn:"Dubai Creek", category:"attractions", subcategory:"landmark", description:"תעלה היסטורית, הלב הפועם של דובאי הישנה, עם שייט באברה מסורתית.", image:"images/attractions/208.jpg", rating:4.4, price:"$", priceRange:"₪1-10 אברה", address:"Deira / Bur Dubai", lat:25.2637, lng:55.3020, tags:["ציון דרך","היסטורי","אברה"], featured:false },
    { id:209, name:"גן הפרחים", nameEn:"Dubai Miracle Garden", category:"attractions", subcategory:"landmark", description:"גן הפרחים הגדול בעולם עם יצירות פרחוניות של מיליוני פרחים.", image:"images/attractions/209.jpg", rating:4.5, price:"$", priceRange:"₪55", address:"Al Barsha South", lat:25.0601, lng:55.2414, tags:["ציון דרך","פרחים","צילום"], featured:true },
    // === MUSEUMS ===
    { id:210, name:"מוזיאון העתיד", nameEn:"Museum of the Future", category:"attractions", subcategory:"museum", description:"מוזיאון עתידני מרהיב המציג חזונות וטכנולוגיות שיעצבו את עולם המחר.", image:"images/attractions/210.jpg", rating:4.8, price:"$$", priceRange:"₪149", address:"Sheikh Zayed Road", lat:25.2197, lng:55.2822, phone:"+971-4-554-0049", tags:["מוזיאון","טכנולוגיה","ארכיטקטורה"], featured:true },
    { id:211, name:"אקוריום דובאי", nameEn:"Dubai Aquarium & Underwater Zoo", category:"attractions", subcategory:"museum", description:"אקוריום ענק בתוך דובאי מול עם מנהרת זכוכית וסיורי צלילה.", image:"images/attractions/211.jpg", rating:4.6, price:"$$", priceRange:"₪130-200", address:"Downtown Dubai", lat:25.1977, lng:55.2790, tags:["מוזיאון","אקוריום","משפחות"], featured:false },
    { id:212, name:"Dubai Garden Glow", nameEn:"Dubai Garden Glow", category:"attractions", subcategory:"museum", description:"פארק אמנות לילי קסום עם תצוגות אור ופסלים מבריקים.", image:"images/nightlife/night_5.jpeg", rating:4.3, price:"$", priceRange:"₪65", address:"Zabeel Park", lat:25.2303, lng:55.3022, tags:["מוזיאון","אור","לילה"], featured:false },
    // === BEACHES ===
    { id:213, name:"חוף JBR", nameEn:"JBR Beach", category:"attractions", subcategory:"beach", description:"חוף ים פתוח ופופולרי לאורך שדרת JBR עם מסעדות ופעילויות.", image:"images/attractions/213.jpg", rating:4.5, price:"חינם", priceRange:"חינם", address:"JBR", lat:25.0785, lng:55.1335, tags:["חוף","חינם","משפחות"], featured:true },
    { id:214, name:"Kite Beach", nameEn:"Kite Beach", category:"attractions", subcategory:"beach", description:"חוף מודרני פופולרי בין גולשי עפיפון עם מתקני ספורט.", image:"images/attractions/214.jpg", rating:4.4, price:"חינם", priceRange:"חינם", address:"Umm Suqeim", lat:25.1564, lng:55.1918, tags:["חוף","ספורט","עפיפון"], featured:false },
    { id:215, name:"La Mer", nameEn:"La Mer", category:"attractions", subcategory:"beach", description:"אזור בילוי חופי מודרני בסגנון בוהמי עם חנויות, מסעדות ופארק מים.", image:"images/nightlife/night_6.jpeg", rating:4.3, price:"חינם", priceRange:"חינם (פעילויות בתשלום)", address:"Jumeirah 1", lat:25.2194, lng:55.2591, tags:["חוף","בוהמי","בילוי"], featured:false },
    // === WATERPARKS ===
    { id:216, name:"Aquaventure", nameEn:"Aquaventure Waterpark", category:"attractions", subcategory:"waterpark", description:"פארק מים מרגש על הפאלם עם מגלשות אדרנלין ואטרקציות לכל הגילאים.", image:"images/hotels/hotel_2.jpeg", rating:4.7, price:"$$$", priceRange:"₪299-395", address:"Palm Jumeirah", lat:25.1306, lng:55.1171, tags:["פארק מים","מגלשות","משפחות"], featured:true },
    { id:217, name:"Wild Wadi", nameEn:"Wild Wadi Waterpark", category:"attractions", subcategory:"waterpark", description:"פארק מים פופולרי עם מגלשות ובריכות גלים בנוף פנטסטי.", image:"images/attractions/217.jpg", rating:4.5, price:"$$", priceRange:"₪225-295", address:"Jumeirah", lat:25.1411, lng:55.1855, tags:["פארק מים","גלים","כיף"], featured:false },
    // === THEME PARKS ===
    { id:218, name:"IMG Worlds", nameEn:"IMG Worlds of Adventure", category:"attractions", subcategory:"theme-park", description:"פארק שעשועים מקורה מהגדולים בעולם עם אזורי מארוול ודינוזאורים.", image:"images/hotels/hotel_14.jpeg", rating:4.4, price:"$$$", priceRange:"₪345-399", address:"City of Arabia", lat:25.0778, lng:55.2978, tags:["פארק שעשועים","מקורה","מארוול"], featured:true },
    { id:219, name:"Ski Dubai", nameEn:"Ski Dubai", category:"attractions", subcategory:"theme-park", description:"אתר סקי מקורה עם מדרונות שלג אמיתיים בלב המדבר!", image:"images/attractions/219.jpg", rating:4.5, price:"$$", priceRange:"₪200-350", address:"Mall of the Emirates", lat:25.1181, lng:55.2002, tags:["פארק שעשועים","סקי","שלג"], featured:true },
    { id:220, name:"Global Village", nameEn:"Global Village", category:"attractions", subcategory:"theme-park", description:"פסטיבל תרבות ובידור בינלאומי ענק המציג תרבויות של עשרות מדינות.", image:"images/attractions/220.jpg", rating:4.5, price:"$", priceRange:"₪25", address:"Sheikh Mohammed Bin Zayed Rd", lat:25.0706, lng:55.3047, tags:["פארק שעשועים","תרבות","פסטיבל"], featured:false },
    // === TOURS ===
    { id:221, name:"ספארי מדבר", nameEn:"Desert Safari", category:"attractions", subcategory:"tour", description:"סיור מרתק בחולות המדבר הכולל רכיבה על דיונות, ארוחת ערב בדואית.", image:"images/hotels/hotel_22.jpeg", rating:4.7, price:"$$", priceRange:"₪150-300", address:"Dubai Desert", lat:24.9964, lng:55.4209, tags:["סיור","מדבר","הרפתקה"], featured:true },
    { id:222, name:"סיור הליקופטר", nameEn:"Helicopter Tour", category:"attractions", subcategory:"tour", description:"סיור מרהיב מעל דובאי בהליקופטר עם נוף על ברג' חליפה והפאלם.", image:"images/hotels/hotel_13.jpeg", rating:4.8, price:"$$$$", priceRange:"₪625-1,500", address:"Dubai", lat:25.2532, lng:55.3657, tags:["סיור","הליקופטר","נוף"], featured:false },
    { id:223, name:"סיור סירת מנוע", nameEn:"Speedboat Tour", category:"attractions", subcategory:"tour", description:"סיור מהיר ומרגש בסירת מנוע עם נוף על קו הרקיע.", image:"images/nightlife/night_1.jpeg", rating:4.5, price:"$$", priceRange:"₪200-400", address:"Dubai Marina", lat:25.0804, lng:55.1404, tags:["סיור","סירה","אדרנלין"], featured:false },
    { id:224, name:"סיור שוק הזהב", nameEn:"Gold Souk Tour", category:"attractions", subcategory:"tour", description:"שוק זהב מסורתי ומפורסם בדיירה עם מאות חנויות תכשיטים.", image:"images/shopping/shop_2.jpeg", rating:4.3, price:"חינם", priceRange:"חינם", address:"Deira", lat:25.2700, lng:55.3047, tags:["סיור","זהב","שוק"], featured:false },
    // === ZOO ===
    { id:225, name:"ספארי פארק דובאי", nameEn:"Dubai Safari Park", category:"attractions", subcategory:"zoo", description:"גן חיות גדול ומודרני הביתה לאלפי בעלי חיים בסביבות טבעיות.", image:"images/hotels/hotel_22.jpeg", rating:4.4, price:"$", priceRange:"₪50", address:"Al Warqa", lat:25.1657, lng:55.4159, tags:["גן חיות","חיות","משפחות"], featured:false },
  ],
  shopping: [
    { id:301, name:"Dubai Mall", nameEn:"Dubai Mall", category:"shopping", subcategory:"mall", description:"הקניון הגדול בעולם! מעל 1,200 חנויות, אקוריום, החלקה על קרח.", image:"images/shopping/301.jpg", rating:4.8, price:"$-$$$$$", priceRange:"כל טווח מחירים", address:"Downtown Dubai", lat:25.1985, lng:55.2796, tags:["קניון","יוקרה","משפחות"], featured:true },
    { id:302, name:"Mall of the Emirates", nameEn:"Mall of the Emirates", category:"shopping", subcategory:"mall", description:"600+ חנויות עם Ski Dubai - מתחם סקי מקורה בלב המדבר!", image:"images/shopping/302.jpg", rating:4.6, price:"$$-$$$$", priceRange:"כל טווח מחירים", address:"Sheikh Zayed Road", lat:25.1181, lng:55.2005, tags:["קניון","סקי","בידור"], featured:true },
    { id:303, name:"Cityland Mall", nameEn:"Cityland Mall", category:"shopping", subcategory:"mall", description:"הקניון הגדול בעולם בקומה אחת! 1.2 מיליון מ\"ר עם גינה בוטנית.", image:"images/shopping/shop_4.jpeg", rating:4.4, price:"$$-$$$", priceRange:"כל טווח מחירים", address:"Dubai Land", lat:25.0650, lng:55.3050, tags:["קניון","ענק","גינה"], featured:true },
    { id:304, name:"Dubai Hills Mall", nameEn:"Dubai Hills Mall", category:"shopping", subcategory:"mall", description:"קניון חדש (2022) עם רכבת הרים מקורה הכי מהירה בעולם!", image:"images/shopping/304.jpg", rating:4.5, price:"$$-$$$", priceRange:"כל טווח מחירים", address:"Dubai Hills", lat:25.1290, lng:55.2430, tags:["קניון","חדש","רכבת הרים"], featured:true },
    { id:305, name:"Dubai Festival City", nameEn:"Dubai Festival City Mall", category:"shopping", subcategory:"mall", description:"קניון על קו המים עם טיילת, מזרקות ומופע אור מרהיב.", image:"images/shopping/305.jpg", rating:4.5, price:"$$-$$$", priceRange:"כל טווח מחירים", address:"Festival City", lat:25.2218, lng:55.3508, tags:["קניון","טיילת","מזרקות"], featured:false },
    { id:306, name:"Ibn Battuta Mall", nameEn:"Ibn Battuta Mall", category:"shopping", subcategory:"mall", description:"מעוצב כמסע של אבן בטוטה עם 6 אזורים: סין, הודו, פרס, מצרים, תוניס, אנדלוסיה.", image:"images/shopping/306.jpg", rating:4.4, price:"$$", priceRange:"מחירים בינוניים", address:"Jebel Ali", lat:25.0440, lng:55.1190, tags:["קניון","תרבות","עיצוב"], featured:false },
    { id:307, name:"City Walk", nameEn:"City Walk", category:"shopping", subcategory:"mall", description:"אזור קניות פתוח בסגנון אירופאי עם בוטיקים, מסעדות וגלריות.", image:"images/shopping/shop_8.jpeg", rating:4.5, price:"$$$", priceRange:"יוקרתי", address:"Jumeirah", lat:25.2074, lng:55.2480, tags:["קניון","פתוח","בוטיק"], featured:false },
    { id:308, name:"Nakheel Mall", nameEn:"Nakheel Mall", category:"shopping", subcategory:"mall", description:"קניון על הפאלם עם נוף מרהיב, מסעדות שף ובריכות.", image:"images/shopping/shop_9.jpeg", rating:4.3, price:"$$-$$$", priceRange:"בינוני-יוקרתי", address:"Palm Jumeirah", lat:25.1124, lng:55.1390, tags:["קניון","פאלם","נוף"], featured:false },
    { id:309, name:"Mercato Mall", nameEn:"Mercato Mall", category:"shopping", subcategory:"mall", description:"קניון בסגנון איטלקי רנסנסי עם חנויות אופנה ומסעדות.", image:"images/shopping/309.jpg", rating:4.2, price:"$$", priceRange:"מחירים בינוניים", address:"Jumeirah", lat:25.2170, lng:55.2530, tags:["קניון","איטלקי","אופנה"], featured:false },
    { id:310, name:"Wafi Mall", nameEn:"Wafi Mall", category:"shopping", subcategory:"mall", description:"קניון בעיצוב מצרי עתיק עם פירמידות, חנויות יוקרה ומסעדות.", image:"images/shopping/310.jpg", rating:4.3, price:"$$-$$$", priceRange:"בינוני-יוקרתי", address:"Oud Metha", lat:25.2308, lng:55.3148, tags:["קניון","מצרי","יוקרה"], featured:false },
    // === SOUKS ===
    { id:311, name:"Gold Souk", nameEn:"Gold Souk", category:"shopping", subcategory:"souk", description:"שוק הזהב המפורסם. מאות חנויות תכשיטים במחירים תחרותיים.", image:"images/shopping/311.jpg", rating:4.5, price:"$$-$$$$", priceRange:"תלוי בקנייה", address:"Deira", lat:25.2867, lng:55.2968, tags:["שוק","זהב","תכשיטים"], featured:true },
    { id:312, name:"Spice Souk", nameEn:"Spice Souk", category:"shopping", subcategory:"souk", description:"שוק התבלינים ההיסטורי. ריחות מדהימים ותבלינים מכל העולם.", image:"images/shopping/312.jpg", rating:4.3, price:"$", priceRange:"זול מאוד", address:"Deira", lat:25.2696, lng:55.2988, tags:["שוק","תבלינים","מסורתי"], featured:false },
    { id:313, name:"Textile Souk", nameEn:"Textile Souk", category:"shopping", subcategory:"souk", description:"שוק הבדים של בר דובאי. בדים, פשמינה וחליפות בהזמנה אישית.", image:"images/shopping/313.jpg", rating:4.2, price:"$-$$", priceRange:"זול-בינוני", address:"Bur Dubai", lat:25.2633, lng:55.2975, tags:["שוק","בדים","מסורתי"], featured:false },
    { id:314, name:"Perfume Souk", nameEn:"Perfume Souk", category:"shopping", subcategory:"souk", description:"שוק הבשמים של דיירה. עוד, בשמים ערביים ושמנים אתריים.", image:"images/shopping/shop_14.jpeg", rating:4.1, price:"$-$$$", priceRange:"זול-יקר", address:"Deira", lat:25.2700, lng:55.2950, tags:["שוק","בשמים","עוד"], featured:false },
    { id:315, name:"Souk Madinat", nameEn:"Souk Madinat Jumeirah", category:"shopping", subcategory:"souk", description:"שוק יוקרתי בסגנון ערבי מסורתי עם תעלות, גלריות ומסעדות.", image:"images/shopping/315.jpg", rating:4.6, price:"$$$", priceRange:"יוקרתי", address:"Madinat Jumeirah", lat:25.1348, lng:55.1863, tags:["שוק","יוקרה","תעלות"], featured:true },
  ],
  nightlife: [
    { id:401, name:"White Dubai", nameEn:"White Dubai", category:"nightlife", subcategory:"club", description:"אחד המועדונים הכי מפורסמים בדובאי. DJ-ים בינלאומיים.", image:"images/nightlife/night_1.jpeg", rating:4.5, price:"$$$", priceRange:"₪200-500 / $55-136", address:"Meydan Racecourse", lat:25.1665, lng:55.3052, tags:["מועדון","DJ","לילה"], featured:true },
    { id:402, name:"Atmosphere Lounge", nameEn:"Atmosphere Lounge", category:"nightlife", subcategory:"lounge", description:"בר בקומה 122 של ברג' חליפה. קוקטיילים בגובה.", image:"images/nightlife/night_2.jpeg", rating:4.7, price:"$$$$", priceRange:"₪300-700 / $82-190", address:"Burj Khalifa, Floor 122", lat:25.1972, lng:55.2744, tags:["בר","תצפית","יוקרה"], featured:true },
    { id:403, name:"Ain Dubai", nameEn:"Ain Dubai", category:"nightlife", subcategory:"entertainment", description:"הגלגל הענק הגבוה בעולם (250 מטר).", image:"images/nightlife/403.jpg", rating:4.6, price:"$$", priceRange:"₪130-500 / $35-136", address:"Bluewaters Island", lat:25.0797, lng:55.1193, tags:["גלגל ענק","תצפית","רומנטי"], featured:true },
    { id:404, name:"La Perle Show", nameEn:"La Perle by Dragone", category:"nightlife", subcategory:"show", description:"מופע אקרובטי מרהיב עם אפקטים של מים ואש.", image:"images/nightlife/night_4.jpeg", rating:4.8, price:"$$$", priceRange:"₪300-700 / $82-190", address:"Al Habtoor City", lat:25.1850, lng:55.2448, tags:["מופע","אקרובטיקה","משפחות"], featured:true },
  ],
  transport: [
    { id:501, name:"מטרו דובאי", nameEn:"Dubai Metro", category:"transport", subcategory:"metro", description:"רשת מטרו אוטומטית. הקו האדום והירוק מכסים את רוב נקודות העניין. קנו Nol Card!", image:"images/transport/501.jpg", rating:4.4, price:"$", priceRange:"₪3-8.5 / $1-2.3 לנסיעה", address:"תחנות בכל דובאי", lat:25.2048, lng:55.2708, tags:["מטרו","זול","נוח"], featured:true },
    { id:502, name:"מוניות דובאי", nameEn:"Dubai Taxi RTA", category:"transport", subcategory:"taxi", description:"מוניות רשמיות בצבע קרם. אמינות ונוחות.", image:"images/transport/502.jpg", rating:4.2, price:"$$", priceRange:"₪12 בסיס + ₪2/ק\"מ", address:"בכל מקום", lat:25.2048, lng:55.2708, tags:["מונית","נוח","24/7"], featured:false },
    { id:503, name:"Water Taxi / Abra", nameEn:"Water Taxi Abra", category:"transport", subcategory:"boat", description:"סירות עץ מסורתיות חוצות את Dubai Creek ב-1 דירהם!", image:"images/transport/503.jpg", rating:4.6, price:"$", priceRange:"₪1 / $0.27 לנסיעה", address:"Dubai Creek", lat:25.2633, lng:55.2975, tags:["סירה","מסורתי","זול"], featured:true },
    { id:504, name:"Careem / Uber", nameEn:"Careem Uber", category:"transport", subcategory:"app", description:"שירותי הסעות באפליקציה. Careem הוא המקומי הפופולרי.", image:"https://images.pexels.com/photos/29352929/pexels-photo-29352929.jpeg", rating:4.3, price:"$$", priceRange:"₪15-100 / $4-27 לנסיעה", address:"בכל מקום", lat:25.2048, lng:55.2708, tags:["אפליקציה","נוח","מהיר"], featured:false },
  ],
  casino: [
    { id:601, name:"Wynn Resort (בקרוב)", nameEn:"Wynn Resort Dubai", category:"casino", subcategory:"casino", description:"ריזורט קזינו ראשון באמירויות! צפוי להיפתח ב-2027.", image:"https://images.pexels.com/photos/31824217/pexels-photo-31824217.jpeg", rating:0, price:"$$$$", priceRange:"טרם פורסם", address:"Ras Al Khaimah", lat:25.1500, lng:55.2000, tags:["קזינו","חדש","יוקרה"], featured:true },
    { id:602, name:"מרוצי סוסים - Meydan", nameEn:"Meydan Racecourse", category:"casino", subcategory:"racing", description:"מתחם מרוצי הסוסים היוקרתי של דובאי. Dubai World Cup - הפרס הגדול בעולם.", image:"images/casino/602.jpg", rating:4.4, price:"$$$", priceRange:"₪100-500", address:"Meydan", lat:25.1665, lng:55.3052, tags:["מרוצים","סוסים","VIP"], featured:true },
    { id:603, name:"מרוצי גמלים", nameEn:"Al Marmoom Camel Racing", category:"casino", subcategory:"racing", description:"מרוצי גמלים מסורתיים עם רובוטים רוכבים. חוויה אמיראתית ייחודית וחינמית!", image:"images/hotels/hotel_22.jpeg", rating:4.6, price:"חינם", priceRange:"חינם", address:"Al Marmoom", lat:25.0200, lng:55.3500, tags:["מרוצים","גמלים","מסורתי"], featured:true },
    { id:604, name:"F1 - Abu Dhabi GP", nameEn:"Abu Dhabi Grand Prix", category:"casino", subcategory:"sport", description:"גרנד פרי פורמולה 1 במסלול יאס מרינה. האירוע הספורטיבי הגדול ביותר במזה\"ת.", image:"images/nightlife/night_1.jpeg", rating:4.8, price:"$$$$", priceRange:"₪1,000-10,000", address:"Yas Marina Circuit, Abu Dhabi", lat:24.4672, lng:54.6031, tags:["ספורט","F1","אירוע"], featured:true },
    { id:605, name:"Dubai World Cup", nameEn:"Dubai World Cup", category:"casino", subcategory:"racing", description:"גביע העולם למרוצי סוסים - הפרס הגדול בעולם ($12 מיליון). מרץ בכל שנה.", image:"images/casino/605.jpg", rating:4.7, price:"$$$", priceRange:"₪200-2,000", address:"Meydan Racecourse", lat:25.1665, lng:55.3052, tags:["מרוצים","סוסים","גביע"], featured:false },
    { id:606, name:"פולו דובאי", nameEn:"Dubai Polo Club", category:"casino", subcategory:"sport", description:"מועדון הפולו של דובאי. משחקים, אירועי VIP וברנץ' ביום שישי.", image:"images/hotels/hotel_5.jpeg", rating:4.3, price:"$$", priceRange:"₪100-500", address:"Arabian Ranches", lat:25.0600, lng:55.2800, tags:["ספורט","פולו","VIP"], featured:false },
    { id:607, name:"גולף - Emirates GC", nameEn:"Emirates Golf Club", category:"casino", subcategory:"sport", description:"מועדון הגולף המפורסם של דובאי עם מסלול 18 גומות ומועדון VIP.", image:"images/hotels/hotel_6.jpeg", rating:4.5, price:"$$$", priceRange:"₪500-1,500", address:"Emirates Hills", lat:25.0950, lng:55.1600, tags:["ספורט","גולף","מועדון"], featured:false },
    { id:608, name:"קרטינג - Dubai Autodrome", nameEn:"Dubai Autodrome", category:"casino", subcategory:"sport", description:"מסלול מרוצים ומתחם קרטינג מקצועי. חוויית אדרנלין לכל הגילאים.", image:"images/nightlife/night_3.jpeg", rating:4.4, price:"$$", priceRange:"₪150-400", address:"Motor City", lat:25.0500, lng:55.2200, tags:["ספורט","קרטינג","אדרנלין"], featured:false },
  ]
};

const PRACTICAL_INFO = {
  emergency: { police:"999", ambulance:"998", fire:"997", tourist_police:"+971-800-2438" },
  currency: { name:"דירהם (AED)", rate:"1 ₪ ≈ 1 AED | 1$ ≈ 3.67 AED", tip:"טיפ 10-15% מקובל" },
  visa: "ישראלים מקבלים ויזה אוטומטית בכניסה (30 יום). דרכון בתוקף ל-6 חודשים.",
  weather: "חודשים מומלצים: נובמבר-מרץ (20-30°C). הקיץ חם מאוד (40-50°C).",
  phrases: [
    { he:"שלום", ar:"سلام / مرحبا", pron:"סאלאם / מרחבא" },
    { he:"תודה", ar:"شكراً", pron:"שוכראן" },
    { he:"כמה זה עולה?", ar:"بكم هذا؟", pron:"בכם האד'א?" },
    { he:"כן / לא", ar:"نعم / لا", pron:"נעם / לא" },
    { he:"סליחה", ar:"عفواً", pron:"עפוואן" },
    { he:"אני רוצה...", ar:"أريد...", pron:"אוריד..." },
    { he:"איפה..?", ar:"أين..؟", pron:"אין..?" },
    { he:"יופי / מצוין", ar:"ممتاز", pron:"מומתאז" },
  ],
  tips: [
    "הלבוש: לבוש צנוע במקומות ציבוריים. בחוף ובבריכה - רגיל.",
    "אלכוהול: מותר רק בברים ומסעדות מורשות. אסור ברחוב.",
    "צילום: אסור לצלם אנשים מקומיים ללא רשות.",
    "רמדאן: נא להימנע מאכילה ושתייה ברחוב בשעות הצום.",
    "Nol Card: קנו בשדה התעופה - עובד על מטרו, אוטובוסים ומוניות מים.",
    "שבת: הכל פתוח 7 ימים בשבוע.",
    "כשרות: יש מספר מסעדות כשרות בדובאי.",
  ]
};

const DB_VERSION = 104;
function getDB() {
  const ver = localStorage.getItem(DB_KEY + '_ver');
  if (ver && Number(ver) >= DB_VERSION) {
    const stored = localStorage.getItem(DB_KEY);
    if (stored) return JSON.parse(stored);
  }
  localStorage.setItem(DB_KEY, JSON.stringify(DEFAULT_DATA));
  localStorage.setItem(DB_KEY + '_ver', DB_VERSION);
  return { ...DEFAULT_DATA };
}

function saveDB(data) {
  localStorage.setItem(DB_KEY, JSON.stringify(data));
}

function getAllItems(category) {
  return getDB()[category] || [];
}

function getItem(category, id) {
  return getAllItems(category).find(item => item.id === Number(id));
}

function addItem(category, item) {
  const db = getDB();
  if (!db[category]) db[category] = [];
  item.id = Date.now();
  db[category].push(item);
  saveDB(db);
  return item;
}

function updateItem(category, id, updates) {
  const db = getDB();
  const idx = db[category].findIndex(item => item.id === Number(id));
  if (idx >= 0) {
    db[category][idx] = { ...db[category][idx], ...updates };
    saveDB(db);
    return db[category][idx];
  }
  return null;
}

function deleteItem(category, id) {
  const db = getDB();
  db[category] = db[category].filter(item => item.id !== Number(id));
  saveDB(db);
}

function getFeatured() {
  const db = getDB();
  const all = [];
  for (const cat of Object.keys(db)) {
    all.push(...db[cat].filter(i => i.featured));
  }
  return all;
}

function searchAll(query) {
  const db = getDB();
  const q = query.toLowerCase();
  const results = [];
  for (const cat of Object.keys(db)) {
    results.push(...db[cat].filter(i =>
      i.name?.toLowerCase().includes(q) ||
      i.nameEn?.toLowerCase().includes(q) ||
      i.description?.toLowerCase().includes(q) ||
      i.tags?.some(t => t.includes(q))
    ));
  }
  return results;
}

function getStats() {
  const db = getDB();
  return {
    hotels: db.hotels?.length || 0,
    restaurants: db.restaurants?.length || 0,
    attractions: db.attractions?.length || 0,
    shopping: db.shopping?.length || 0,
    nightlife: db.nightlife?.length || 0,
    transport: db.transport?.length || 0,
    casino: db.casino?.length || 0,
    total: Object.values(db).reduce((sum, arr) => sum + arr.length, 0)
  };
}
